import {useState} from 'react';
import data from '../../../shared/paper-adaptive-projection-ui-v1.json';
import ProjectionNativeDemo,{type ProjectionCase} from './ProjectionNativeDemo';
import {useComparisonAnchor} from './useComparisonAnchor';
import './PaperProjectionResults.css';
type Site=Omit<ProjectionCase,'pairs'>&{pairs:(ProjectionCase['pairs'][number]&{adaptive:string})[]};
const report=data as unknown as {cases:Site[];report_sha256:string;native_models:number;native_queries:number;package:{filename:string;bytes:number;sha256:string}};
const base='/research/paper-adaptive-projection-v1/',drop=(a:number,b:number)=>100*(1-a/b);
const methods=[{id:'p1',label:'原 Iₜ 贪心 / 顶点插值'},{id:'pt',label:'旧 Pₜ / 原 Iₜ 网格'},{id:'adaptive',label:'新 Pₜ / 全过程自适应贪心'},{id:'before',label:'原方向面带'},{id:'fitted',label:'GUGIS / 原空间共享系数拟合'},{id:'p2',label:'原层级 P₂ 高阶控制'}] as const;
export default function AdaptivePaperResults(){
  useComparisonAnchor('paper-adaptive-results');
  const [field,setField]=useState('anisotropic-quartic'),[angle,setAngle]=useState(30),[budget,setBudget]=useState(2048),[demo,setDemo]=useState(false);
  const cases=report.cases.filter(c=>c.field.id===field),site=cases.find(c=>c.angle_degrees===angle)!,pair=site.pairs.find(p=>p.budget===budget)!,a=site.models[pair.adaptive],b=site.models[pair.fitted],old=site.models[pair.before],fixed=site.models[pair.pt],p2=site.models[pair.p2];
  const rows=cases.flatMap(c=>c.pairs.map(p=>({c,p,a:c.models[p.adaptive],b:c.models[p.fitted]}))),wins=rows.filter(r=>r.b.e2_m2<r.a.e2_m2).length,max=Math.max(...methods.map(m=>site.models[pair[m.id]].e2_m2));
  return <section id="paper-adaptive-results" className="pf-results" aria-labelledby="pa-title"><div className="cr-heading"><div><span className="cr-eyebrow">完整区域贪心 / Pₜ 的 L₂ 优先级 / 公式 (2.18) 插值 L₁ 选边</span><h2 id="pa-title">{field==='anisotropic-quartic'?'更强的自适应三角对照，仍保留面带优势。':'较均衡曲面：同时查看未获益的结果。'}</h2><p>这次由 Pₜ 投影误差驱动整个细分过程，重新选区域、生成独立网格；分裂边严格沿用论文的插值 L₁ 决策。原两类函数、七个角度、九档预算全部保留，已有 GUGIS 模型未根据新结果重新择优。当前函数 {wins}/63 组拟合面带 E₂ 更低。</p></div><div className="hs-selects"><label>固定源函数<select aria-label="自适应Pₜ对照函数" value={field} onChange={e=>setField(e.target.value)}><option value="anisotropic-quartic">强各向异性四次曲面</option><option value="published-quartic">原较均衡四次曲面</option></select></label><label>原角度<select aria-label="自适应Pₜ对照角度" value={angle} onChange={e=>setAngle(Number(e.target.value))}>{cases.map(c=><option key={c.id} value={c.angle_degrees}>{c.angle_degrees}°</option>)}</select></label><label>原预算<select aria-label="自适应Pₜ对照预算" value={budget} onChange={e=>setBudget(Number(e.target.value))}>{site.pairs.map(p=><option key={p.budget} value={p.budget}>N = {p.budget.toLocaleString()}</option>)}</select></label></div></div>
    <div className="hs-metrics"><article><span>GUGIS 对新自适应 Pₜ · 全域 E₂</span><strong>{Math.abs(drop(b.e2_m2,a.e2_m2)).toFixed(2)}%<small>{b.e2_m2<a.e2_m2?'降低':'升高'}</small></strong><p>{b.e2_m2.toExponential(5)} / {a.e2_m2.toExponential(5)} m²</p></article><article><span>同空间原面带 → 拟合面带</span><strong>{drop(b.e2_m2,old.e2_m2).toFixed(2)}%<small>降低</small></strong><p>{old.binary_bytes.toLocaleString()} → {b.binary_bytes.toLocaleString()} B · 拓扑不变</p></article><article><span>全角度与预算 · 当前源函数</span><strong>{wins}/63</strong><p>低于完整 Pₜ 区域贪心的全域 E₂</p></article></div>
    <div className="pf-bars" aria-label="六种保存模型的全域误差，包含完整自适应Pₜ和更准确的P₂">{methods.map(m=>{const e=site.models[pair[m.id]];return <div className={`pf-bar pf-${m.id}`} key={m.id}><span>{m.label}</span><i style={{width:`${100*e.e2_m2/max}%`}}/><output>{e.e2_m2.toExponential(4)} m²</output></div>;})}</div>
    <div className="cr-table"><table><caption>同一 100 × 100 m 源函数 · 公开实际文件与记录数量</caption><thead><tr><th>方法</th><th>完整文件</th><th>全域 E₂ / m²</th><th>实际控制点 / 原生记录</th></tr></thead><tbody>{methods.map(m=>{const e=site.models[pair[m.id]];return <tr key={m.id}><th>{m.label}</th><td>{e.binary_bytes.toLocaleString()} B</td><td>{e.e2_m2.toExponential(6)}</td><td>{e.points.toLocaleString()} / {e.records.toLocaleString()}</td></tr>;})}</tbody></table></div>
    <p className="pf-control">新 Pₜ 相比固定网格 Pₜ 的 E₂ {a.e2_m2<=fixed.e2_m2?'降低':'升高'} {Math.abs(drop(a.e2_m2,fixed.e2_m2)).toFixed(3)}%；网格过程没有复用原 Iₜ 优先级。P₂ 当前 E₂ 为 {p2.e2_m2.toExponential(5)} m²，{p2.e2_m2<b.e2_m2?'仍比拟合面带更准确':'当前未优于拟合面带'}。N 是新 Pₜ 的实际三角形数量和原 GUGIS 选择上限；原面带还保持较严格的旧 Iₜ 文件预算。实际文件大小不相等。</p>
    <div className="cr-actions"><button aria-label="展开完整自适应Pₜ原生对照" aria-expanded={demo} onClick={()=>setDemo(v=>!v)}>{demo?'收起原生对照':'打开旧 Pₜ / 新自适应 Pₜ / GUGIS 同色标查询'}</button><a download href={`${base}${site.id}/${a.binary_filename}`}>新自适应 Pₜ 原生文件 ↗</a><a download href={`${base}${report.package.filename}`}>全部126组完整证据 ZIP ↗</a></div>
    {demo&&<ProjectionNativeDemo site={site} entries={[{label:methods[1].label,model:fixed},{label:methods[2].label,model:a},{label:methods[4].label,model:b}]}/>}
    <details className="cr-details"><summary>当前函数全部 63 组，包含不利预算</summary><div className="cr-table"><table><caption>全七角度、九档原预算，禁止只显示获益的结果</caption><thead><tr><th>角度 / N</th><th>GUGIS E₂</th><th>自适应 Pₜ E₂</th><th>误差降低</th><th>两种实际完整文件</th></tr></thead><tbody>{rows.map(({c,p,a,b})=><tr key={c.id+p.budget}><th>{c.angle_degrees}° / {p.budget}</th><td>{b.e2_m2.toExponential(4)}</td><td>{a.e2_m2.toExponential(4)}</td><td>{drop(b.e2_m2,a.e2_m2).toFixed(3)}%</td><td>{b.binary_bytes.toLocaleString()} / {a.binary_bytes.toLocaleString()} B</td></tr>)}</tbody></table></div><img src={`${base}adaptive-projection-results.svg`} loading="lazy" width="1100" height="670" alt="两类曲面全部126组相对完整自适应Pₜ的误差降低，保留全部正负值"/></details>
    <details className="cr-details"><summary>对应论文的具体算法、完整细分记录与独立核验</summary><p><a href="https://arxiv.org/pdf/1101.1452" target="_blank" rel="noreferrer">原论文 §2.1、§2.4 与公式 (2.18)</a>：区域最大 Pₜ 局部 L₂ 平方误差，边决策最小两个子三角形的 Iₜ 插值 L₁ 误差总和。这两个算子保持区分。初始两三角形、每次中点二分、数值平局顺序、全部选择记录和源函数均可复查；两种严格凸四次函数以 Float64 精确多项式求积到舍入误差。没有运行作者原始软件或复制论文的数值表。</p><p>全部 {report.native_models} 个模型通过独立五节点积分、保存平面的投影正交性、完整区域/选边轨迹核验及 {report.native_queries.toLocaleString()} 次原生高程/梯度查询。Pₜ 允许分片不连续；独立 XYZ 的重复点如实计入，并非最小平面系数编码。拟合面带仍保持 C⁰；P₂ 和旧失败原型保留在既有证据包中。这是固定有限预算实验，不宣称渐近理论优越性、真实地面误差、连续最大误差、RAM/GPU 或 ArcGIS 软件性能。</p><div className="cr-actions">{[['protocol.json','预先固定算法与观察披露'],['all-methods.csv','全部126组六方法CSV'],['results.json','所有保存模型与对照'],['independent-audit.json','独立积分与完整轨迹核验'],['native-audit.json','原生查询核验'],[`${site.id}/refinement-trace.json`,'当前样例的全部2046次细分']].map(([file,label])=><a key={file} download href={`${base}${file}`}>{label} ↗</a>)}</div><p className="cr-hash">结果 SHA-256：{report.report_sha256}<br/>完整证据 ZIP SHA-256：{report.package.sha256}</p></details>
  </section>;
}
