import {useState} from 'react';
import data from '../../../shared/diagonal-hybrid-ui-v1.json';
import DiagonalSourceDemo,{type DiagonalReceipt,type DiagonalSite} from './DiagonalSourceDemo';
import {useComparisonAnchor} from './useComparisonAnchor';
import './DiagonalHybridResults.css';
const report=data as unknown as {cases:DiagonalSite[];native_models:number;native_queries:number;seam_height_pairs:number;report_sha256:string;package:{filename:string;sha256:string;bytes:number}};
const base='/research/diagonal-hybrid-v1/';
const methods=[{id:'p1-local',label:'P1 · 两种对角线择优',prior:false},{id:'hybrid-local',label:'GUGIS · 三类单元混合',prior:false},{id:'p1',label:'P1 · 固定对角线',prior:true},{id:'ruled',label:'仅直纹面带',prior:true},{id:'hybrid',label:'原两类单元混合',prior:true}];
const reduction=(a:number,b:number)=>100*(1-a/b),size=(n:number)=>(n/1000).toFixed(2)+' kB',name=(s:DiagonalSite)=>s.name.replace(' · 英国环境署裸地 DTM','');
function selected(site:DiagonalSite,row:DiagonalSite['byte_pairs'][number]|DiagonalSite['target_pairs'][number],method:typeof methods[number]){const id=method.prior?row.prior[method.id]:row[method.id as 'p1-local'|'hybrid-local'];return id?site.models[id]:null;}
function ByteCurve({site,budget}:{site:DiagonalSite;budget:number}){
  const all=site.byte_pairs.flatMap(p=>methods.map(m=>selected(site,p,m))).filter((e):e is DiagonalReceipt=>!!e),floor=1e-8,minimum=Math.floor(Math.log10(Math.max(floor,Math.min(...all.filter(e=>e.e2_m2>floor).map(e=>e.e2_m2))))),maximum=Math.ceil(Math.log10(Math.max(...all.map(e=>e.e2_m2)))),span=Math.max(1,maximum-minimum),x=(v:number)=>52+598*(Math.log2(v)-8)/(Math.log2(135528)-8),y=(v:number)=>22+220*(maximum-Math.max(minimum,Math.log10(Math.max(floor,v))))/span;
  const colours=['#6589a6','#278d74','#a9b8c1','#c09d65','#935f9a'];
  return <svg className="ds-byte-curve" viewBox="0 0 700 295" role="img" aria-label="当前真实样区的十档完整字节预算与全域误差对比曲线"><line x1={x(budget)} x2={x(budget)} y1="20" y2="244" stroke="#d1ded6" strokeDasharray="4 4"/>{Array.from({length:span+1},(_,i)=>maximum-i).map(v=><g key={v}><line x1="52" x2="650" y1={y(10**v)} y2={y(10**v)} stroke="#edf1ed"/><text x="46" y={y(10**v)+4} textAnchor="end">10^{v}</text></g>)}{methods.map((m,i)=><g key={m.id}><path d={site.byte_pairs.map((p,j)=>{const e=selected(site,p,m)!;return `${j?'L':'M'}${x(p.byte_ceiling)},${y(e.e2_m2)}`;}).join(' ')} fill="none" stroke={colours[i]} strokeWidth={i===1?2.5:1.4} strokeDasharray={m.prior?'4 3':undefined}/>{site.byte_pairs.map(p=>{const e=selected(site,p,m)!;return <circle key={p.byte_ceiling} cx={x(p.byte_ceiling)} cy={y(e.e2_m2)} r={i===1?3.3:2.3} fill={colours[i]}><title>{`${m.label} · 上限 ${p.byte_ceiling} B · 实际 ${e.binary_bytes} B · E₂ ${e.e2_m2.toExponential(6)} m²`}</title></circle>;})}</g>)}{[256,1024,4096,16384,65536,135528].map(v=><text key={v} x={x(v)} y="263" textAnchor="middle">{v>=1024?`${(v/1024).toFixed(v===135528?1:0)} KiB`:`${v} B`}</text>)}<text x="52" y="287">完整文件预算（横轴 log₂） · E₂（纵轴 log₁₀；零误差位于下边界）</text></svg>;
}
export default function DiagonalHybridResults(){
  useComparisonAnchor('diagonal-hybrid-results');
  const [id,setId]=useState(report.cases[0].id),[mode,setMode]=useState<'budget'|'target'>('budget'),[budget,setBudget]=useState(8192),[target,setTarget]=useState(.1),[demo,setDemo]=useState(false),site=report.cases.find(c=>c.id===id)!,row=mode==='budget'?site.byte_pairs.find(p=>p.byte_ceiling===budget)!:site.target_pairs.find(p=>p.height_target_m===target)!,a=selected(site,row,methods[0]),b=selected(site,row,methods[1]);
  const fixed=report.cases.map(c=>{const p=c.byte_pairs.find(p=>p.byte_ceiling===8192)!;return {a:selected(c,p,methods[0])!,b:selected(c,p,methods[1])!};}),fixedWins=fixed.filter(p=>p.b.e2_m2<p.a.e2_m2).length,fixedDrops=fixed.map(p=>reduction(p.b.e2_m2,p.a.e2_m2));
  const all=report.cases.flatMap(c=>c.byte_pairs.map(p=>({a:selected(c,p,methods[0])!,b:selected(c,p,methods[1])!}))),allWins=all.filter(p=>p.b.e2_m2<p.a.e2_m2).length;
  const current=report.cases.map(c=>{const p=c.byte_pairs.find(p=>p.byte_ceiling===budget)!;return {a:selected(c,p,methods[0])!,b:selected(c,p,methods[1])!};}),wins=current.filter(p=>p.b.e2_m2<p.a.e2_m2).length;
  const entries=[methods[0],methods[4],methods[1]].flatMap(m=>{const e=selected(site,row,m);return e?[{label:m.label,model:e}]:[];});
  return <section id="diagonal-hybrid-results" className="ds-results" aria-labelledby="ds-title"><div className="cr-heading"><div><span className="cr-eyebrow">更强三角对照 / 两种对角线 / 实际分组成本</span><h2 id="ds-title">允许三角带转向，再检验混合表达的优势。</h2><p>不再只比较固定方向的三角带。每个单元可选择两种对角线；GUGIS 可在直纹面及两种三角带之间选择。固定 8,192 B 上限下，{fixedWins} / 20 个原始样区的混合 E₂ 更低；全部十档预算为 {allWins} / 200。二十个样区的误差降低范围为 {Math.min(...fixedDrops).toFixed(4)}%–{Math.max(...fixedDrops).toFixed(4)}%，负值表示混合更差。</p></div><div className="hs-selects"><label>固定真实样区<select aria-label="双对角线真实样区" value={id} onChange={e=>setId(e.target.value)}>{report.cases.map(c=><option key={c.id} value={c.id}>{name(c)}</option>)}</select></label><label>比较条件<select aria-label="双对角线比较条件" value={mode} onChange={e=>setMode(e.target.value as 'budget'|'target')}><option value="budget">同一完整文件预算</option><option value="target">同一连续最大误差目标</option></select></label>{mode==='budget'?<label>完整字节上限<select aria-label="双对角线文件预算" value={budget} onChange={e=>setBudget(Number(e.target.value))}>{site.byte_pairs.map(p=><option key={p.byte_ceiling} value={p.byte_ceiling}>{p.byte_ceiling.toLocaleString()} B</option>)}</select></label>:<label>源函数误差上限<select aria-label="双对角线误差目标" value={target} onChange={e=>setTarget(Number(e.target.value))}>{site.target_pairs.map(p=><option key={p.height_target_m} value={p.height_target_m}>{100*p.height_target_m} cm</option>)}</select></label>}</div></div>
    <div className="hs-metrics"><article><span>{mode==='budget'?'当前样区 · 对两方向 P1 的 E₂ 降幅':'当前样区 · 对两方向 P1 的完整文件减少'}</span><strong>{a&&b?`${Math.abs(reduction(mode==='budget'?b.e2_m2:b.binary_bytes,mode==='budget'?a.e2_m2:a.binary_bytes)).toFixed(2)}%`:'无可比模型'}<small>{a&&b?((mode==='budget'?b.e2_m2:b.binary_bytes)<(mode==='budget'?a.e2_m2:a.binary_bytes)?'更少':(mode==='budget'?b.e2_m2:b.binary_bytes)===(mode==='budget'?a.e2_m2:a.binary_bytes)?'相同':'更多'):''}</small></strong><p>{a&&b?mode==='budget'?`${b.e2_m2.toExponential(4)} / ${a.e2_m2.toExponential(4)} m²`:`${size(b.binary_bytes)} / ${size(a.binary_bytes)}`:'固定候选中未达到目标，保留缺失结果。'}</p></article><article><span>当前混合模型 · 三类单元</span><strong>{b?.ruled_cells??'—'}<small>直纹面</small></strong><p>{b?`${b.minus_cells} 负向 + ${b.plus_cells} 正向三角单元`:'无符合目标的混合模型'}</p></article><article><span>{mode==='budget'?'当前预算 · 全部二十个原始样区':'当前混合模型 · 连续最大误差上界'}</span><strong>{mode==='budget'?`${wins}/20`:b?`${(100*b.continuous_bound_m).toFixed(3)} cm`:'—'}</strong><p>{mode==='budget'?'混合 E₂ 数值低于两种对角线 P1':'全域极值核验 + 已声明 Float64 裕量'}</p></article></div>
    <div className="cr-table"><table><caption>{mode==='budget'?`同一完整文件上限 ${budget.toLocaleString()} B，实际文件大小可能不同`:`同一源函数连续最大误差目标 ${100*target} cm，分别选择最小可行文件`}</caption><thead><tr><th>方法</th><th>完整文件</th><th>全域 E₂ / m²</th><th>最大误差上界</th><th>直纹 / 两方向三角单元</th></tr></thead><tbody>{methods.map(m=>{const e=selected(site,row,m);return <tr key={m.id} data-method={m.id}><th>{m.label}</th>{e?<><td>{e.binary_bytes.toLocaleString()} B</td><td>{e.e2_m2.toExponential(4)}</td><td>{(100*e.continuous_bound_m).toFixed(3)} cm</td><td>{e.ruled_cells} / {e.minus_cells} / {e.plus_cells}</td></>:<td colSpan={4}>固定候选中未找到达到目标的模型</td>}</tr>;})}</tbody></table></div>
    <details className="cr-details"><summary>当前样区的十档完整预算曲线</summary><ByteCurve site={site} budget={budget}/><p>蓝：两方向 P1 · 绿：三类混合 · 灰：固定方向 P1 · 金：仅直纹面 · 紫：原两类混合。每档选择该方法在 49 个网格中满足上限且 E₂ 最低的文件；横轴是预算上限，实际文件字节见图中点的说明。零误差使用图底部标记，不修改原始指标。</p></details>
    <div className="cr-actions"><button aria-label="展开双对角线原生查询" aria-expanded={demo} onClick={()=>setDemo(v=>!v)}>{demo?'收起两种对角线与原生查询':'查看真实单元分布与同色标误差'}</button>{b&&<a download href={`${base}${site.id}/${b.binary_filename}`}>当前三类混合原生模型 ↗</a>}<a download href={`${base}${site.id}/source-window.tif`}>原始一米 GeoTIFF 样窗 ↗</a><a download href={`${base}${report.package.filename}`}>完整新旧对照证据 ZIP ↗</a></div>
    {demo&&<DiagonalSourceDemo site={site} entries={entries}/>}
    <details className="cr-details"><summary>全部二十个原始样区，包括不获优势与缺失模型</summary><div className="cr-table"><table><caption>{mode==='budget'?`完整文件预算 ${budget.toLocaleString()} B`:`连续最大源函数误差目标 ${100*target} cm`} · 无样区筛选</caption><thead><tr><th>真实样区</th><th>两方向 P1 · B / E₂</th><th>三类混合 · B / E₂</th><th>{mode==='budget'?'E₂ 降低':'完整字节减少'}</th></tr></thead><tbody>{report.cases.map(c=>{const p=mode==='budget'?c.byte_pairs.find(p=>p.byte_ceiling===budget)!:c.target_pairs.find(p=>p.height_target_m===target)!,a=selected(c,p,methods[0]),b=selected(c,p,methods[1]);return <tr key={c.id}><th>{name(c)}</th><td>{a?`${a.binary_bytes.toLocaleString()} / ${a.e2_m2.toExponential(3)}`:'无符合目标的候选'}</td><td>{b?`${b.binary_bytes.toLocaleString()} / ${b.e2_m2.toExponential(3)}`:'无符合目标的候选'}</td><td>{a&&b?`${reduction(mode==='budget'?b.e2_m2:b.binary_bytes,mode==='budget'?a.e2_m2:a.binary_bytes).toFixed(3)}%`:'不作数值比较'}</td></tr>;})}</tbody></table></div><img src={`${base}diagonal-hybrid-results.svg`} loading="lazy" width="1100" height="915" alt="固定8192字节预算下全部二十个原始样区的新旧混合方法与两对角线P1误差比"/></details>
    <p className="hs-scope">这是固定整数张量网格上的源函数比较。局部按积分误差选择单元，再从 49 个网格筛选完整成本可行的模型；没有声称对全体混合分组或网格实现全局最优。论文的自适应贪心 P1 对标另见主结果，不将本实验当作论文算法或 ArcGIS 软件测速。原始像素、BNG / ODN 约定及源单位元数据警告保留；这不是实测地面精度。</p>
    <details className="cr-details"><summary>核验范围、固定协议和原始可复算数据</summary><p>先固定协议、数值平局规则和单元解析恒等式，再计算全部 {report.native_models.toLocaleString()} 个新模型。两种对角线的极值都计入最大误差；独立五节点积分使用已保存模型的实际角点高程。原生内核完成 {report.native_queries.toLocaleString()} 次内部及源节点查询，核验 {report.seam_height_pairs.toLocaleString()} 对共享边界高程。方向切换产生的每条记录和索引均计入文件；C⁰ 连续，梯度可跳变。</p><div className="cr-actions">{[['protocol.json','预先固定协议'],['selections.csv','全部预算和误差目标 CSV'],['results.json','全部1960个模型的结果'],['native-audit.json','两种对角线原生核验'],['integral-audit.json','独立全域积分核验'],['prior-hybrid-source-evidence.zip','完整原两类混合实验']].map(([file,label])=><a key={file} download href={`${base}${file}`}>{label} ↗</a>)}</div><p className="cr-hash">结果 SHA-256：{report.report_sha256}<br/>完整证据 ZIP SHA-256：{report.package.sha256}</p></details>
  </section>;
}
