import {useEffect,useMemo,useState} from 'react';
import report from '../../../shared/hybrid-source-ui-v1.json';
import {loadHybridSourceModel} from './loadHybridSourceModel';
import {loadSourceModel} from './loadSourceModel';
import {prepareSourceBandQuery,prepareRegularGridQuery,type SourceBandModel,type RegularHeightGrid} from './sourceRuledBandMath';
import {useComparisonAnchor} from './useComparisonAnchor';
import './HybridSourceResults.css';
const base='/research/hybrid-source-v1/',labels:Record<string,string>={p1:'P1 三角带',ruled:'纯直纹面带',hybrid:'局部混合表达'};
type Site=typeof report.cases[number];
type Receipt={method:string;binary_filename:string;binary_bytes:number;binary_sha256:string;ruled_cells:number;p1_triangles:number};
const percent=(a:number,b:number)=>100*(1-a/b),size=(n:number)=>(n/1000).toFixed(2)+' kB';
const fixedPairs=report.cases.map(c=>c.byte_pairs.find(p=>p.byte_ceiling===8192)!);
const fixedReductions=fixedPairs.map(p=>percent(p.hybrid.e2_m2,p.p1.e2_m2));
const allPairs=report.cases.flatMap(c=>c.byte_pairs),allWins=allPairs.filter(p=>p.hybrid.e2_m2<p.p1.e2_m2).length;
const heatCoordinates=Array.from({length:17},(_,i)=>Number((-32+(i+.5)*64/17).toFixed(2)));
function errorColour(value:number,scale:number){const t=Math.min(1,Math.abs(value)/scale),zero=[248,250,247],end=value<0?[94,142,174]:[190,113,72];return `rgb(${zero.map((v,i)=>Math.round(v+(end[i]-v)*t)).join(',')})`;}
function ModelDemo({site,entries}:{site:Site;entries:Receipt[]}){
  const [loaded,setLoaded]=useState<{models:SourceBandModel[];grid:RegularHeightGrid}|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[x,setX]=useState(.27),[y,setY]=useState(-1.41);
  const key=entries.map(e=>e.binary_filename).join(',');
  useEffect(()=>{const abort=new AbortController();setLoaded(null);setError('');
    Promise.all([Promise.all(entries.map(e=>loadHybridSourceModel(`${base}${site.id}/${e.binary_filename}`,e.binary_bytes,e.binary_sha256,site.origin_bng,abort.signal))),loadSourceModel(site.regular_grid.url,site.regular_grid.bytes,site.regular_grid.sha256,site.origin_bng,abort.signal)]).then(([models,source])=>{if(source.kind!=='grid')throw new Error('原始源高程格类型不符');if(!abort.signal.aborted)setLoaded({models,grid:source.model});}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'读取失败');});return()=>abort.abort();
  },[site.id,key,retry]);
  const functions=useMemo(()=>loaded?.models.map(prepareSourceBandQuery)??null,[loaded]),source=useMemo(()=>loaded?prepareRegularGridQuery(loaded.grid):null,[loaded]);
  const heatmaps=useMemo(()=>functions&&source?functions.map(fn=>heatCoordinates.flatMap((yy,j)=>heatCoordinates.map((xx,i)=>({x:xx,y:yy,i,j,delta:fn.query(xx,yy)!.height-source.query(xx,yy)!.height})))):[],[functions,source]);
  const heatMaximum=heatmaps.length?Math.max(...heatmaps.flatMap(m=>m.map(p=>Math.abs(p.delta)))):0,heatScale=Math.max(.001,heatMaximum);
  if(error)return <p role="alert">{error} <button onClick={()=>setRetry(v=>v+1)}>重试混合源地形模型</button></p>;
  if(!loaded||!functions||!source)return <p role="status">正在校验当前原生模型和原始 Float32 源高程格…</p>;
  const low=Math.min(...loaded.grid.values),high=Math.max(...loaded.grid.values),centre=(low+high)/2,ratio=Math.min(8,80/(2.2*Math.max(.00001,(high-low)/2))),reference=source.query(x,y)!,project=(x:number,y:number,z:number)=>[150+2.2*(x-y),190-1.1*(x+y)-2.2*ratio*(z-centre)];
  return <div className="hs-demo"><div className="pr-query-controls">{(['X','Y'] as const).map((name,i)=><label key={name}>局部 {name} / m<input type="range" aria-label={`混合源地形同点查询${name}`} min="-31.9" max="31.9" step=".01" value={i?y:x} onChange={e=>(i?setY:setX)(Number(e.target.value))}/><output>{(i?y:x).toFixed(2)}</output></label>)}</div><p>同一点 · BNG E {reference.easting.toFixed(2)} / N {reference.northing.toFixed(2)} m · 原始源函数 Z {reference.height.toFixed(6)} m ODN</p><div className="hs-native-models">{loaded.models.map((model,i)=>{
    const fn=functions[i],q=fn.query(x,y)!,entry=entries[i];let paths='';for(let direction=0;direction<2;direction++)for(let line=0;line<=16;line++)for(let step=0;step<=16;step++){const xx=-32+4*(direction?line:step),yy=-32+4*(direction?step:line),point=project(xx,yy,fn.query(xx,yy)!.height);paths+=`${step?'L':'M'}${point[0]},${point[1]}`;}
    const point=project(x,y,q.height);return <article key={entry.method}><h3>{labels[entry.method]}</h3><p>{size(entry.binary_bytes)} · {entry.ruled_cells} 个面带单元 / {entry.p1_triangles} 个三角面</p><svg role="img" aria-label={`${labels[entry.method]}已保存原生函数的三维展示采样`} viewBox="0 0 300 350"><path d={paths} fill="none" stroke={entry.method==='p1'?'#718ca2':entry.method==='ruled'?'#b29866':'#288c76'} strokeWidth=".65"/><circle cx={point[0]} cy={point[1]} r="4" fill="#d16e51" stroke="white"/><text x="12" y="334">64 × 64 m · 同一垂直比例 {ratio.toFixed(1)}×</text></svg><p className="hs-point">Z {q.height.toFixed(6)} m<br/>相对源函数 Δz {(1000*(q.height-reference.height)).toFixed(3)} mm<br/>坡度 {(Math.atan(Math.hypot(...q.gradient))*180/Math.PI).toFixed(4)}°</p><div className="hs-heatmap"><h4>相对同一源函数的误差</h4><svg role="img" aria-label={`${labels[entry.method]}同色阶源函数误差热图，点击同步查询或使用上方滑条键盘操作`} viewBox="0 0 300 300">{heatmaps[i].map(p=><rect key={p.i+17*p.j} data-x={p.x} data-y={p.y} data-delta={p.delta} x={27+14.4*p.i} y={12+14.4*(16-p.j)} width="14.45" height="14.45" fill={errorColour(p.delta,heatScale)} onClick={()=>{setX(p.x);setY(p.y);}}><title>{`X ${p.x.toFixed(2)} / Y ${p.y.toFixed(2)} m · Δz ${(1000*p.delta).toFixed(4)} mm`}</title></rect>)}<circle cx={27+244.8*(x+32)/64} cy={12+244.8*(32-y)/64} r="4" fill="none" stroke="#193f37" strokeWidth="1.5" pointerEvents="none"/><text x="27" y="278" className="hs-heat-scale">统一色阶 ±{(1000*heatScale).toFixed(3)} mm</text><text x="27" y="295">蓝：模型较低 · 白：接近源值 · 橙：较高</text></svg></div></article>;
  })}</div><p>线框为 17 × 17 的展示采样，不是文件中的存储单元。高程和梯度直接查询原生面带或三角函数，范围、垂直比例和查询点一致。每幅热图使用相同的 289 个内部点和统一色阶，点击色块可同步查询；上方滑条支持键盘操作。最低色阶为 ±1 mm，三种模型在这些点的最大绝对差为 {(1000*heatMaximum).toFixed(4)} mm。这是展示抽样，不能替代上方独立积分与连续最大误差界。</p>{loaded.models.map((model,i)=>entries[i].method==='hybrid'?<div className="hs-distribution" key={i}><svg role="img" viewBox="0 0 340 360" aria-label="当前真实混合模型的面带和三角带原生类型分布">{model.patches.map((p,k)=>{const ids=p.kind==='ruled-strip'?[...p.left,...p.right]:p.kind==='triangle-strip'?p.indices:[],points=ids.map(n=>model.points[n]),xmin=Math.min(...points.map(p=>p[0])),xmax=Math.max(...points.map(p=>p[0])),ymin=Math.min(...points.map(p=>p[1])),ymax=Math.max(...points.map(p=>p[1]));return <rect key={k} x={10+5*(xmin+32)} y={10+5*(32-ymax)} width={5*(xmax-xmin)} height={5*(ymax-ymin)} fill={p.kind==='ruled-strip'?'#48a38c':'#7296b1'} stroke="white" strokeWidth=".5"/>;})}<text x="10" y="350">绿色：面带 · 蓝色：三角带 · 按连续原生记录合并</text></svg><p>这是当前文件的真实类型分布。共享边界节点与相同线性边界函数保持 C⁰；法向导数可以跳变。</p></div>:null)}</div>;
}
export default function HybridSourceResults(){
  useComparisonAnchor('hybrid-source-results');
  const [siteId,setSiteId]=useState(report.cases[0].id),[mode,setMode]=useState<'budget'|'target'>('budget'),[budget,setBudget]=useState(8192),[target,setTarget]=useState(.1),[demo,setDemo]=useState(false),site=report.cases.find(c=>c.id===siteId)!,row=mode==='budget'?site.byte_pairs.find(p=>p.byte_ceiling===budget)!:site.target_pairs.find(p=>p.height_target_m===target)!,b=row.hybrid,a=row.p1;
  const entries=[row.p1,row.ruled,row.hybrid].filter((e):e is NonNullable<typeof e>=>e!==null),all=report.cases.map(c=>c.byte_pairs.find(p=>p.byte_ceiling===budget)!),wins=all.filter(p=>p.hybrid.e2_m2<p.p1.e2_m2).length;
  return <section id="hybrid-source-results" className="hs-results" aria-labelledby="hs-title"><div className="cr-heading"><div><span className="cr-eyebrow">真实源 DTM / 直纹面带 + 三角带 / C⁰ 连接</span><h2 id="hs-title">同一预算下，真实地形误差还能更低。</h2><p>固定 8,192 B 上限下，全部 20 / 20 个源样区的 E₂ 比本次网格 P1 降低 {Math.min(...fixedReductions).toFixed(2)}%–{Math.max(...fixedReductions).toFixed(2)}%；全部十档预算共 {allWins} / {allPairs.length} 组更低。每个样区检查 49 个网格、三种方法，类型切换增加的记录与索引也计入文件。</p></div><div className="hs-selects"><label>固定真实样区<select aria-label="混合源地形样区" value={siteId} onChange={e=>setSiteId(e.target.value)}>{report.cases.map(c=><option key={c.id} value={c.id}>{c.name.replace(' · 英国环境署裸地 DTM','')}</option>)}</select></label><label>比较条件<select aria-label="混合源地形比较条件" value={mode} onChange={e=>setMode(e.target.value as 'budget'|'target')}><option value="budget">相同完整文件预算</option><option value="target">相同连续最大误差目标</option></select></label>{mode==='budget'?<label>文件上限<select aria-label="混合源地形文件预算" value={budget} onChange={e=>setBudget(Number(e.target.value))}>{site.byte_pairs.map(p=><option key={p.byte_ceiling} value={p.byte_ceiling}>{p.byte_ceiling.toLocaleString()} B</option>)}</select></label>:<label>源函数最大差<select aria-label="混合源地形误差目标" value={target} onChange={e=>setTarget(Number(e.target.value))}>{site.target_pairs.map(p=><option key={p.height_target_m} value={p.height_target_m}>{p.height_target_m*100} cm</option>)}</select></label>}</div></div>
    <div className="hs-metrics"><article><span>{mode==='budget'?'当前混合相对 P1 · 全域 E₂':'当前混合相对全分辨率源面带 · 文件'}</span><strong>{mode==='budget'?`${Math.abs(percent(b.e2_m2,a!.e2_m2)).toFixed(1)}%`:`${percent(b.binary_bytes,site.full_source_ruled_bytes).toFixed(1)}%`}<small>{mode==='budget'?(b.e2_m2<a!.e2_m2?'降低':'更高'):'减少'}</small></strong><p>{mode==='budget'?`${b.e2_m2.toExponential(3)} / ${a!.e2_m2.toExponential(3)} m²`:`${size(b.binary_bytes)} / ${size(site.full_source_ruled_bytes)}`} · 混合 / 参考</p></article><article><span>当前实际混合类型</span><strong>{b.ruled_cells}<small>个面带单元</small></strong><p>{b.p1_triangles} 个三角面 · {b.stored_points} 个共享节点</p></article><article><span>{mode==='budget'?'当前文件预算 · 全部固定样区':'当前源函数连续最大误差界'}</span><strong>{mode==='budget'?`${wins}/20`:`${(100*b.continuous_bound_m).toFixed(3)} cm`}</strong><p>{mode==='budget'?'混合 E₂ 小于选定 P1 的样区数':'含数值余量；这是源函数误差受控的简化'}</p></article></div>
    <div className="cr-table"><table><caption>{mode==='budget'?`完整文件均不超过 ${budget.toLocaleString()} B，实际用量可以不同`:`每个可用模型相对源函数的连续最大差均不超过 ${100*target} cm`}</caption><thead><tr><th>方法</th><th>完整文件</th><th>全域 E₂ m²</th><th>连续最大差界</th><th>面带单元 / 三角面</th></tr></thead><tbody>{(['p1','ruled','hybrid'] as const).map(k=>{const e=row[k];return <tr key={k}><th>{labels[k]}</th>{e?<><td>{e.binary_bytes.toLocaleString()} B</td><td>{e.e2_m2.toExponential(4)}</td><td>{(e.continuous_bound_m*100).toFixed(3)} cm</td><td>{e.ruled_cells} / {e.p1_triangles}</td></>:<td colSpan={4}>固定候选中没有达到此目标的模型</td>}</tr>;})}</tbody></table></div>
    <p className="hs-scope">此处比较同一源双线性函数上的有限张量网格。P1 是这里的固定网格三角方法，没有复用论文式贪心细分；混合按局部 E₂ 选类型，因此不一定获得最小文件或最小最大差。较低误差若需要更多分组记录，预算内收益也可能失去。</p><div className="cr-actions"><button aria-expanded={demo} aria-label="展开混合源地形原生查询" onClick={()=>setDemo(v=>!v)}>{demo?'收起混合源地形原生查询':'查看真实混合结构与同点查询'}</button><a download href={`${base}${site.id}/${b.binary_filename}`}>当前混合原生模型 ↗</a><a download href={`${base}${site.id}/source-window.tif`}>原始一米 GeoTIFF 输入 ↗</a><a download href={`${base}${report.package.filename}`}>二十样区完整证据 ZIP ↗</a></div>
    {demo&&<ModelDemo key={site.id+mode+budget+target} site={site} entries={entries}/>}
    <details className="cr-details"><summary>全部二十样区在当前比较条件下的结果</summary><div className="cr-table"><table><caption>{mode==='budget'?`文件上限 ${budget.toLocaleString()} B`:`源函数最大差目标 ${100*target} cm`} · 全部样区保留</caption><thead><tr><th>固定样区</th><th>混合文件</th><th>混合 E₂ m²</th><th>连续最大差界</th><th>P1 文件 / E₂</th><th>真正混合</th></tr></thead><tbody>{report.cases.map(c=>{const p=mode==='budget'?c.byte_pairs.find(p=>p.byte_ceiling===budget)!:c.target_pairs.find(p=>p.height_target_m===target)!,e=p.hybrid;return <tr key={c.id}><th>{c.name.replace(' · 英国环境署裸地 DTM','')}</th><td>{size(e.binary_bytes)}</td><td>{e.e2_m2.toExponential(3)}</td><td>{(100*e.continuous_bound_m).toFixed(3)} cm</td><td>{p.p1?`${size(p.p1.binary_bytes)} / ${p.p1.e2_m2.toExponential(3)}`:'无合格候选'}</td><td>{e.ruled_cells>0&&e.p1_triangles>0?'面带 + 三角带':e.ruled_cells>0?'仅面带':'仅三角带'}</td></tr>;})}</tbody></table></div><img src={`${base}hybrid-source-results.svg`} loading="lazy" width="1100" height="915" alt="全部二十真实源地形的固定字节预算误差与10厘米连续误差目标文件对比，保留失利和缺失候选"/></details>
    <details className="cr-details"><summary>来源、连接规则与完整误差核验</summary><p>每个输入均为原先冻结的 65 × 65 Float32 源节点，比较范围是节点之间的 64 × 64 m。节点值不做舍入；BNG、米制/ODN 约定和原始源单位元数据警告均保留。这是源函数差，不是实测地面精度。完整一米源函数的精确保留与这里的误差受控简化分别展示。</p><p>所有单元在同一整数张量网格内共用角点。双线性面带与 P1 三角面沿矩形边界都是相同的线性函数，因此可以 C⁰ 连接，不增加 T 形接点；梯度仍可能跳变。发布独立检查每个相邻单元的两侧边界函数。</p><p>全域 E₂ 逐一积分全部一米源单元。面带残差的最大值在源单元角点；三角面还检查源单元内每段对角线的二次残差极值，避免只看顶点漏掉峰值。独立五节点求积重新计算全部 {report.native_models.toLocaleString()} 个保存模型、每个局部混合选择与最大值；原生内核执行 {report.native_queries.toLocaleString()} 次高程/梯度及源节点查询，另检查 {report.seam_height_pairs.toLocaleString()} 对边界高程。Float64 数值余量不是区间证明。</p><div className="cr-actions">{[['selections.csv','全部预算与误差目标 CSV'],['protocol.json','预先固定协议'],['results.json','所有候选与未通过目标'],['native-audit.json','原生查询与边界审计'],['integral-audit.json','独立全域积分审计']].map(([file,label])=><a download key={file} href={`${base}${file}`}>{label} ↗</a>)}</div><p className="cr-hash">结果 SHA-256：{report.report_sha256}<br/>完整证据 ZIP SHA-256：{report.package.sha256}</p></details>
  </section>;
}
