import {useState} from 'react';
import report from '../../../shared/native-query-repeat-display-v1.json';
import {useComparisonAnchor} from './useComparisonAnchor';
import './QueryStatisticsResults.css';
import './NativeQueryRepeatResults.css';
const base='/research/native-query-repeat-v1/';
const all=report.cases.flatMap(c=>c.repetitions),wins=all.filter(r=>r.ratio>1).length,low=Math.min(...all.map(r=>r.ratio)),high=Math.max(...all.map(r=>r.ratio));
export default function NativeQueryRepeatResults(){
  useComparisonAnchor('native-query-repeat');
  const [id,setId]=useState('piecewise-8'),item=report.cases.find(c=>c.id===id)!,ceiling=Math.ceil(high*10)/10,floor=Math.floor(Math.min(1,low)*10)/10-.1,project=(v:number)=>55+470*(v-floor)/(ceiling-floor);
  return <section className="qs-results nqr-results" id="native-query-repeat" aria-labelledby="nqr-title"><div className="cr-heading"><div><span className="cr-eyebrow">三次独立进程 / 相同原生函数 / 预先固定重复协议</span><h2 id="nqr-title">三次独立进程，查询结果仍有收益。</h2><p>五个固定样例 × 三次新进程，共 {wins} / {all.length} 个耗时中位数对比大于 1。全部实测比值为 {low.toFixed(2)}–{high.toFixed(2)}×；保留每次完整结果，不挑最快的一次。</p></div><label className="qs-selector">查看同一样例的三次结果<select aria-label="独立进程查询样例" value={id} onChange={e=>setId(e.target.value)}>{report.cases.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label></div>
    <div className="qs-metrics"><article><span>当前样例 · 三次实测范围</span><strong>{item.minimum_ratio.toFixed(3)}<small>– {item.maximum_ratio.toFixed(3)}×</small></strong><p>三角耗时中位数 / 面带耗时中位数</p></article><article><span>全部固定样例与进程</span><strong>{wins}<small>/ {all.length} 个对比有收益</small></strong><p>每个样例每次 17 对 · 共 {report.prepared_pairs} 对准备后测量</p></article><article><span>重新构建内核后的独立正确性检查</span><strong>{report.native_queries.toLocaleString()}<small>次查询</small></strong><p>全部高程 / 梯度、边界与域外拒绝通过</p></article></div>
    <div className="nqr-selected"><svg viewBox="0 0 650 180" role="img" aria-label="当前样例三次独立进程耗时中位数比值，大于一表示面带查询较快"><line x1={project(1)} x2={project(1)} y1="12" y2="142" stroke="#aabdb4" strokeDasharray="4 4"/><text x={project(1)} y="166" textAnchor="middle">1.000×</text>{item.repetitions.map((r,i)=><g key={r.repetition}><text x="0" y={35+42*i}>进程 {r.repetition}</text><line x1={project(1)} x2={project(r.ratio)} y1={29+42*i} y2={29+42*i} stroke={['#267e6a','#54768b','#b78e50'][i]} strokeWidth="3"/><circle cx={project(r.ratio)} cy={29+42*i} r="5" fill={['#267e6a','#54768b','#b78e50'][i]}/><text x="551" y={35+42*i}>{r.ratio.toFixed(3)}×</text></g>)}</svg><p>背景为同一零收益参照；这里显示耗时中位数之比，不是配对比值中位数。范围只是三次实测的最小与最大值，不能当作置信区间。</p></div>
    <div className="cr-table"><table><caption>全部五个同函数样例 · 三次顺序执行的新 Node 进程</caption><thead><tr><th>固定样例</th><th>进程 1</th><th>进程 2</th><th>进程 3</th><th>三次实测范围</th></tr></thead><tbody>{report.cases.map(c=><tr key={c.id}><th>{c.name}</th>{c.repetitions.map(r=><td key={r.repetition}>{r.ratio.toFixed(3)}×</td>)}<td>{c.minimum_ratio.toFixed(3)}–{c.maximum_ratio.toFixed(3)}×</td></tr>)}</tbody></table></div>
    <p className="qs-scope">本机 Windows i7-14650HX / Node v24.13.0 的 CPU 点定位、高程和解析梯度查询。两个旧例分别对照 P₂ / P₃，三个分段例对照 P₃，双方表示同一源函数。未测试论文作者软件或 ArcGIS；不是浏览器/GPU 帧率。顺序执行避免本任务构建和数值审计同时运行，后台系统负载仍不受控；三次结果不保证跨设备性能。</p>
    <details className="cr-details"><summary>当前样例每次实际耗时、配对胜负及完整科学图</summary><div className="cr-table"><table><thead><tr><th>独立进程</th><th>面带中位数 ns</th><th>三角中位数 ns</th><th>配对胜负</th><th>每次实际查询数</th></tr></thead><tbody>{item.repetitions.map(r=><tr key={r.repetition}><th>{r.repetition}</th><td>{r.ruled_median_ns.toFixed(3)}</td><td>{r.triangles_median_ns.toFixed(3)}</td><td>{r.paired_wins} 胜 / {r.paired_losses} 负</td><td>{r.queries_per_trial.toLocaleString()}</td></tr>)}</tbody></table></div><img src={`${base}native-repeat-results.svg`} loading="lazy" width="1100" height="650" alt="五个固定CPU查询样例在三次独立进程的全部十五个中位数比值；展示实测范围而非置信区间"/></details>
    <details className="cr-details"><summary>复测协议、不可变源代码与完整原始计时</summary><p>保留原始计时循环、4,096 个固定内部点、五批预热、17 对准备后 / 五对旧内核试验和交替执行顺序。双方共用每例标定出的循环次数，上限 128。仅构建适配器与仓库路径解析发生变化，独立审计逐字节恢复原始计时正文，并重新构建实际编译内核核对全部三次产物。</p><p>全部 {report.raw_records} 行原始记录均公开；每次均可单独下载 CSV 和报告。范围没有作独立样本的合并推断，不删掉较小收益。原始 v1 计时与后续统计分析保持独立，<a href="#native-query-statistics">查看原始记录的统计诊断</a>。</p><div className="cr-actions"><a download href={`${base}all-trials.csv`}>三次全部 660 行 CSV ↗</a><a download href={`${base}protocol.json`}>预先固定复测协议 ↗</a><a download href={`${base}native-audit.json`}>独立原生内核审计 ↗</a><a download href={`${base}release-audit.json`}>计时与完整性复核 ↗</a>{[1,2,3].map(n=><a download key={n} href={`${base}run-${n}/results.json`}>进程 {n} 完整结果 ↗</a>)}</div><p className="cr-hash">复测结果 SHA-256：{report.report_sha256}<br/>原始计时 SHA-256：{report.baseline_report_sha256}</p></details>
    <div className="cr-actions"><a download href={`${base}${report.package.filename}`}>三次复测完整证据 ZIP ↗</a><a download href={`${base}native-repeat-results.svg`}>全部复测科学图 SVG ↗</a></div>
  </section>;
}
