import {useState} from 'react';
import data from '../../../shared/paper-projection-ui-v1.json';
import ProjectionNativeDemo,{type ProjectionCase} from './ProjectionNativeDemo';
import {useComparisonAnchor} from './useComparisonAnchor';
import './PaperProjectionResults.css';
const report=data as unknown as {cases:ProjectionCase[];native_models:number;native_queries:number;seam_pairs:number;report_sha256:string;package:{filename:string;bytes:number;sha256:string};prototype_audit:{rejected_models:number;rejected_pairs:number;source_error_worsened_pairs:number;report_sha256:string;package:{filename:string;sha256:string}}};
const base='/research/paper-projection-stable-v1/',auditBase='/research/paper-projection-prototype-audit-v1/',drop=(a:number,b:number)=>100*(1-a/b);
const methods=[{id:'p1',label:'论文式 P1 · 顶点插值'},{id:'pt',label:'Pₜ 正交投影 · 同一三角网'},{id:'before',label:'原面带 · 插值系数'},{id:'fitted',label:'GUGIS · 共享系数 L₂ 拟合'},{id:'p2',label:'既有层级 P2 · 高阶控制'}] as const;
export default function PaperProjectionResults(){
  useComparisonAnchor('paper-projection-results');
  const [field,setField]=useState('anisotropic-quartic'),[angle,setAngle]=useState(30),[budget,setBudget]=useState(2048),[demo,setDemo]=useState(false),cases=report.cases.filter(c=>c.field.id===field),site=cases.find(c=>c.angle_degrees===angle)!,pair=site.pairs.find(p=>p.budget===budget)!,a=site.models[pair.pt],b=site.models[pair.fitted],before=site.models[pair.before],p2=site.models[pair.p2];
  const rows=cases.flatMap(c=>c.pairs.map(p=>({c,p,a:c.models[p.pt],b:c.models[p.fitted],old:c.models[p.before]}))),wins=rows.filter(p=>p.b.e2_m2<p.a.e2_m2).length,fitWins=report.cases.flatMap(c=>c.pairs.map(p=>({b:c.models[p.fitted],a:c.models[p.before]}))).filter(p=>p.b.e2_m2<p.a.e2_m2).length,maximum=Math.max(...methods.map(m=>site.models[pair[m.id]].e2_m2));
  return <section id="paper-projection-results" className="pf-results" aria-labelledby="pf-title"><div className="cr-heading"><div><span className="cr-eyebrow">核心算法升级 / 共享空间 L₂ 拟合 / 论文许可的 Pₜ 强控制</span><h2 id="pf-title">保留连续结构和字节数，把误差进一步压低。</h2><p>只改变共享贝塞尔高程系数，不增加控制点、索引或文件字节。本次全部 {fitWins} / 126 组的拟合 E₂ 比原面带更低；当前曲面的 {wins} / 63 组还低于同一三角网上的 Pₜ 正交投影。P2 高阶控制与未获优势的结果同表保留。</p></div><div className="hs-selects"><label>原有固定曲面<select aria-label="共享拟合曲面" value={field} onChange={e=>setField(e.target.value)}><option value="anisotropic-quartic">强方向性四次曲面</option><option value="published-quartic">既有四次曲面</option></select></label><label>原有源方向<select aria-label="共享拟合源方向" value={angle} onChange={e=>setAngle(Number(e.target.value))}>{cases.map(c=><option key={c.id} value={c.angle_degrees}>{c.angle_degrees}°</option>)}</select></label><label>原有论文式网格预算<select aria-label="共享拟合论文预算" value={budget} onChange={e=>setBudget(Number(e.target.value))}>{site.pairs.map(p=><option key={p.budget} value={p.budget}>N = {p.budget.toLocaleString()}</option>)}</select></label></div></div>
    <div className="hs-metrics"><article><span>对同网格 Pₜ 正交投影 · E₂</span><strong>{Math.abs(drop(b.e2_m2,a.e2_m2)).toFixed(2)}%<small>{b.e2_m2<a.e2_m2?'更低':'更高'}</small></strong><p>{b.e2_m2.toExponential(4)} / {a.e2_m2.toExponential(4)} m²</p></article><article><span>对原面带 · 同空间拟合降幅</span><strong>{drop(b.e2_m2,before.e2_m2).toFixed(2)}%<small>更低</small></strong><p>{before.binary_bytes.toLocaleString()} → {b.binary_bytes.toLocaleString()} B · 未增加字节</p></article><article><span>当前曲面 · 全部方向和九档预算</span><strong>{wins}/63</strong><p>拟合 E₂ 低于固定网格 Pₜ 强控制</p></article></div>
    <div className="pf-bars" aria-label="同一物理范围各方法的实际全域误差">{methods.map(m=>{const e=site.models[pair[m.id]];return <div className={`pf-bar pf-${m.id}`} key={m.id}><span>{m.label}</span><i style={{width:`${100*e.e2_m2/maximum}%`}}/><output>{e.e2_m2.toExponential(4)} m²</output></div>;})}</div><div className="cr-table"><table><caption>同一函数 / 10,000 m² · Pₜ 采用原 P1 网格，面带拟合前后共享完全相同的结构</caption><thead><tr><th>方法</th><th>完整文件</th><th>全域 E₂ / m²</th><th>控制点 / 原生记录</th></tr></thead><tbody>{methods.map(m=>{const e=site.models[pair[m.id]];return <tr key={m.id} data-fit-method={m.id}><th>{m.label}</th><td>{e.binary_bytes.toLocaleString()} B</td><td>{e.e2_m2.toExponential(5)}</td><td>{e.points.toLocaleString()} / {e.records.toLocaleString()}</td></tr>;})}</tbody></table></div>
    <p className="pf-control">P2 控制 E₂ 为 {p2.e2_m2.toExponential(4)} m²；当前拟合面带相对它{b.e2_m2<p2.e2_m2?'更低':'更高'} {Math.abs(drop(b.e2_m2,p2.e2_m2)).toFixed(2)}%。Pₜ 是论文允许的算子，但本实验没有按 Pₜ 误差重新生成自适应网格，不将它称为论文完整算法的最优结果。Pₜ 的分片高程不要求连续，实际 XYZ 重复开销也计入本协议；未声称这是最小平面系数编码。</p>
    <div className="cr-actions"><button aria-label="展开共享拟合原生查询" aria-expanded={demo} onClick={()=>setDemo(v=>!v)}>{demo?'收起拟合前后原生查询':'看拟合前后的同色标误差与原生查询'}</button><a download href={`${base}${site.id}/${b.binary_filename}`}>当前共享拟合原生文件 ↗</a><a download href={`${base}${report.package.filename}`}>全部126组与失败原型证据 ZIP ↗</a></div>{demo&&<ProjectionNativeDemo site={site} entries={[{label:methods[2].label,model:before},{label:methods[1].label,model:a},{label:methods[3].label,model:b}]}/>}
    <details className="cr-details"><summary>当前曲面全部 63 组结果，包括 Pₜ 更好的预算</summary><div className="cr-table"><table><caption>{field==='anisotropic-quartic'?'强方向性':'既有'}四次曲面 · 七个方向 × 九档原有预算</caption><thead><tr><th>方向 / N</th><th>原面带 E₂</th><th>拟合 E₂</th><th>Pₜ E₂</th><th>对 Pₜ 的误差降低</th><th>面带完整字节</th></tr></thead><tbody>{rows.map(({c,p,a,b,old})=><tr key={c.id+p.budget}><th>{c.angle_degrees}° / {p.budget}</th><td>{old.e2_m2.toExponential(3)}</td><td>{b.e2_m2.toExponential(3)}</td><td>{a.e2_m2.toExponential(3)}</td><td>{drop(b.e2_m2,a.e2_m2).toFixed(3)}%</td><td>{b.binary_bytes.toLocaleString()} B</td></tr>)}</tbody></table></div><img src={`${base}paper-projection-results.svg`} loading="lazy" width="1100" height="620" alt="全部126组同空间拟合相对固定三角网Pₜ的误差降低，保留强方向性曲面的一个失利和另一曲面的多数失利"/></details>
    <details className="cr-details"><summary>数值稳定性、完整原型失败记录和独立复算</summary><p>完整原型检查发现 {report.prototype_audit.rejected_models} 个原生模型超出原有内核系数限制，其中 {report.prototype_audit.source_error_worsened_pairs} 组全域误差也恶化。原型的全部文件和结果保留；另附全量原生有效性核验，不将只看残差收敛作为保存成功。</p><p>修复后，极弱支持的控制点保持原高程；相对质量对角线的固定阈值为 10⁻¹⁴。共享系数在受约束子空间中拟合，不是完整空间的全局最优声明；实际保存曲面的误差和原有内核容量再次检查，失败时退回原模型并记录。当前文件用了 {b.fit?.active_controls} 个活跃控制点，{b.fit?.weak_controls_held_at_original_z} 个弱支持点保持原值；{b.fit?.accepted?'拟合已接受':`已回退：${b.fit?.fallback_reason}`}。</p><p>全部 {report.native_models} 个修复后模型通过已冻结原生内核的 {report.native_queries.toLocaleString()} 次查询，并核验 {report.seam_pairs.toLocaleString()} 对物理范围内的共享边界。独立五节点检验保存系数的正交性，独立七节点复算全域误差；先前原型观察和修复协议均明确披露。这里不提供连续最大误差、运行内存、CPU/GPU 或 ArcGIS 软件优势结论。</p><div className="cr-actions">{[['protocol.json','修复前固定协议与观察披露'],['pairs.csv','全部126组 CSV'],['results.json','所有固定控制结果'],['integral-audit.json','独立积分与保存系数正交性'],['native-audit.json','全部修复后原生查询'],['prototype/results.json','完整失败原型结果']].map(([file,label])=><a key={file} download href={`${base}${file}`}>{label} ↗</a>)}<a download href={`${auditBase}${report.prototype_audit.package.filename}`}>完整原型原生有效性核验 ZIP ↗</a></div><p className="cr-hash">结果 SHA-256：{report.report_sha256}<br/>完整证据 ZIP SHA-256：{report.package.sha256}<br/>原型有效性核验 SHA-256：{report.prototype_audit.report_sha256}</p></details>
  </section>;
}
