import {useEffect,useMemo,useState} from 'react';
import {loadProjectionModel} from './loadProjectionModel';
import {loadVariableModel} from './loadVariableModel';
import {loadAdaptiveProjectionModel} from './loadAdaptiveProjectionModel';
import {preparePrincipalQuery,type PrincipalModel} from './principalRuledMath';
export type ProjectionReceipt={method:string;previous:boolean;package?:'variable-curvature-v1'|'paper-projection-stable-v1'|'paper-adaptive-projection-v1';binary_filename:string;binary_bytes:number;binary_sha256:string;e2_m2:number;points:number;records:number;fit?:{accepted:boolean;fallback_reason:string|null;active_controls:number;weak_controls_held_at_original_z:number;inactive_controls_held_at_original_z:number;iterations:number;relative_restricted_galerkin_residual:number}};
export type ProjectionCase={id:string;name:string;field:{id:string;quadratic:number[];quartic:number[]};angle_degrees:number;source_frame:number[][];models:Record<string,ProjectionReceipt>;pairs:{budget:number;p1:string;before:string;p2:string;pt:string;fitted:string}[]};
export function projectionSourceHeight(site:ProjectionCase,x:number,y:number){const frame=site.source_frame,u=x*frame[0][0]+y*frame[1][0],v=x*frame[0][1]+y*frame[1][1];return 30+site.field.quadratic[0]*u*u+site.field.quadratic[1]*v*v+site.field.quartic[0]*u**4+site.field.quartic[1]*v**4;}
const coords=Array.from({length:17},(_,i)=>Number((-50+(i+.5)*100/17).toFixed(2)));
function colour(value:number,scale:number){const t=Math.min(1,Math.abs(value)/scale),zero=[248,250,247],end=value<0?[94,142,174]:[190,113,72];return `rgb(${zero.map((v,i)=>Math.round(v+(end[i]-v)*t)).join(',')})`;}
export default function ProjectionNativeDemo({site,entries}:{site:ProjectionCase;entries:{label:string;model:ProjectionReceipt}[]}){
  const [loaded,setLoaded]=useState<{models:PrincipalModel[];key:string;id:string}|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[x,setX]=useState(.27),[y,setY]=useState(-1.41),key=entries.map(e=>e.model.binary_sha256).join(',');
  useEffect(()=>{const controller=new AbortController();setLoaded(null);setError('');Promise.all(entries.map(({model:e})=>{
    const folder=e.package??(e.previous?'variable-curvature-v1':'paper-projection-stable-v1'),loader=folder==='paper-adaptive-projection-v1'?loadAdaptiveProjectionModel:e.previous?loadVariableModel:loadProjectionModel;
    return loader(`/research/${folder}/${site.id}/${e.binary_filename}`,e.binary_bytes,e.binary_sha256,controller.signal);
  })).then(models=>{if(!controller.signal.aborted)setLoaded({models,key,id:site.id});}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'拟合原生模型读取失败');});return()=>controller.abort();},[site.id,key,retry]);
  const ready=loaded?.key===key&&loaded.id===site.id?loaded:null,functions=useMemo(()=>ready?.models.map(preparePrincipalQuery)??null,[ready]);
  const maps=useMemo(()=>functions?functions.map(fn=>coords.flatMap((yy,j)=>coords.map((xx,i)=>({x:xx,y:yy,i,j,delta:fn.query(xx,yy)!.height-projectionSourceHeight(site,xx,yy)})))):[],[functions,site.id]);
  const scale=Math.max(.001,...maps.flatMap(m=>m.map(p=>Math.abs(p.delta))));
  if(error)return <p role="alert">{error} <button onClick={()=>setRetry(v=>v+1)}>重试拟合原生模型</button></p>;
  if(!ready||!functions)return <p role="status">正在校验同一空间拟合前后及 Pₜ 原生文件…</p>;
  const z=projectionSourceHeight(site,x,y);
  return <div className="pf-native-demo"><div className="pr-query-controls">{(['X','Y'] as const).map((name,i)=><label key={name}>同一局部 {name} / m<input aria-label={`拟合原生同步查询${name}`} type="range" min="-49.9" max="49.9" step=".01" value={i?y:x} onChange={e=>(i?setY:setX)(Number(e.target.value))}/><output>{(i?y:x).toFixed(2)}</output></label>)}</div><p>源解析函数 Z {z.toFixed(6)} m · 同一 100 × 100 m 物理方形 · 同一查询点</p><div className="pf-native-models">{entries.map(({label,model},i)=>{const q=functions[i].query(x,y)!;return <article key={model.method}><h3>{label}</h3><p>{model.binary_bytes.toLocaleString()} B · {model.points.toLocaleString()} 存储控制点</p><svg className="pf-error-map" viewBox="0 0 300 300" role="img" aria-label={`${label}同色标源函数误差热图，点击同步查询`}>{maps[i].map(p=><rect key={p.i+17*p.j} data-x={p.x} data-y={p.y} data-delta={p.delta} x={27+14.4*p.i} y={12+14.4*(16-p.j)} width="14.45" height="14.45" fill={colour(p.delta,scale)} onClick={()=>{setX(p.x);setY(p.y);}}><title>{`X ${p.x.toFixed(2)} / Y ${p.y.toFixed(2)} m · Δz ${(1000*p.delta).toFixed(4)} mm`}</title></rect>)}<circle cx={27+244.8*(x+50)/100} cy={12+244.8*(50-y)/100} r="4" fill="none" stroke="#193f37" strokeWidth="1.5" pointerEvents="none"/><text className="pf-heat-scale" x="27" y="278">统一色标 ±{(1000*scale).toFixed(3)} mm</text><text x="27" y="295">蓝：模型较低 · 白：接近 · 铜：较高</text></svg><p className="pf-query">Z {q.height.toFixed(6)} m<br/>源函数 Δz {(1000*(q.height-z)).toFixed(4)} mm<br/>坡度 {(Math.atan(Math.hypot(...q.gradient))*180/Math.PI).toFixed(4)}°</p></article>;})}</div><p>每张热图用同一组 289 个内部坐标、同一色标。点击色块或使用上方滑块查询已保存的原生函数；这些展示点不是全域误差或连续最大误差认证。拟合面带保持共享边界 C⁰；Pₜ 的独立三角平面不要求连续，其梯度与边界取值遵循原生文件的查询归属。</p></div>;
}
