import {useState} from 'react';
import report from '../../../shared/query-statistics-display-v1.json';
import {useComparisonAnchor} from './useComparisonAnchor';
import './QueryStatisticsResults.css';
const base='/research/query-statistics-v1/';
export default function QueryStatisticsResults(){
  useComparisonAnchor('native-query-statistics');
  const [id,setId]=useState('piecewise-8'),item=report.cases.find(c=>c.id===id)!,supported=report.cases.filter(c=>c.resampling_interval_above_one).length,significant=report.cases.filter(c=>c.significant_holm_005).length;
  return <section id="native-query-statistics" className="qs-results" aria-labelledby="qs-title"><div className="cr-heading"><div><span className="cr-eyebrow">既有 CPU 重复试验 / 后续统计 / 全部五个样例</span><h2 id="qs-title">速度优势，也可以检查重复试验的支持程度。</h2><p>同一已公开数据集，每个样例 17 对交替查询记录。五个样例的 95% 探索性重采样区间均高于 1；配对符号检验经五项 Holm 校正后均低于 0.05。原始计时数据保持不变。</p></div><label className="qs-selector">查看固定样例<select aria-label="查询统计样例" value={id} onChange={e=>setId(e.target.value)}>{report.cases.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>
    <div className="qs-metrics"><article><span>当前样例 · 耗时中位数之比</span><strong>{item.median_ratio.toFixed(2)}<small>×</small></strong><p>{item.triangles_median_ns.toFixed(1)} / {item.ruled_median_ns.toFixed(1)} ns · 三角 / 面带</p></article><article><span>95% 探索性重采样区间</span><strong>{item.bootstrap.low.toFixed(3)}<small>— {item.bootstrap.high.toFixed(3)}</small></strong><p>配对、按先后顺序分层 · 50,000 次重采样</p></article><article><span>全部固定样例的统计诊断</span><strong>{supported}<small>/ 5 区间高于 1</small></strong><p>{significant} / 5 配对符号检验 Holm p &lt; 0.05</p></article></div>
    <div className="cr-table"><table><caption>原始 Windows i7-14650HX / Node v24.13.0 CPU 查询 · 固定五个同函数样例</caption><thead><tr><th>样例</th><th>中位数之比</th><th>95% 重采样区间</th><th>面带更快 / 17 对</th><th>Holm 校正 p</th></tr></thead><tbody>{report.cases.map(c=><tr key={c.id}><th>{c.name}</th><td>{c.median_ratio.toFixed(3)}×</td><td>{c.bootstrap.low.toFixed(3)}–{c.bootstrap.high.toFixed(3)}</td><td>{c.wins} / 17</td><td>{c.holm_adjusted_p.toExponential(3)}</td></tr>)}</tbody></table></div>
    <p className="qs-scope">这是原有记录的后续分析，没有重新计时，也不是计时之前的预注册。重采样和符号检验依赖试验对足够独立、有代表性的假设；串行关联或运行时漂移会影响推断。它们支持本次 CPU 样例的诊断，不提供跨设备、GPU、ArcGIS 软件或真实 DTM 的性能保证。</p>
    <details className="cr-details"><summary>当前样例的执行先后顺序与完整五样例图</summary><div className="qs-orders">{item.execution_orders.map(o=><p key={o.first}><strong>{o.first==='ruled'?'面带先执行':'三角方法先执行'}</strong> · {o.pairs} 对 · 中位数之比 {o.median_ratio.toFixed(3)}×</p>)}</div><img src={`${base}query-statistics-results.svg`} loading="lazy" width="1100" height="620" alt="五个原生CPU查询样例的全部85个配对比值、耗时中位数比及95%探索性重采样区间，并给出Holm符号检验结果"/></details>
    <details className="cr-details"><summary>统计定义、原始记录与确定性复算</summary><p>统计量为三角方法耗时中位数 / 面带耗时中位数，区别于 17 个配对速度比的中位数。每次保留两种方法同一试验编号的配对关系；分别从 9 对面带先执行、8 对三角先执行的层内有放回重采样。固定 PCG64 随机种子，每例 50,000 次，以线性分位数取 2.5% / 97.5% 区间；这是 percentile 方法，不是 BCa。</p><p>另对每对查询谁更快作双侧精确符号检验，去除完全相等的耗时，使用五个固定样例的 Holm stepdown 校正。符号检验检验配对胜负，而区间估计中位数之比，二者衡量不同统计量。方法参考 <a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.bootstrap.html" target="_blank" rel="noreferrer">SciPy 配对重采样定义</a>、<a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binomtest.html" target="_blank" rel="noreferrer">精确二项检验</a>、<a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/p.adjust.html" target="_blank" rel="noreferrer">R 多项检验校正</a>。当前实现仅使用 NumPy / Python 标准库。</p><p>完整原始 220 行记录、85 对准备后试验、全部 250,000 个 Float64 重采样值和原始完整模型证据一并保存。发布逐字节重放所有结果、分布和配对 CSV，独立复核二项分布完整支持集、线性分位数与 Holm 校正。</p><div className="cr-actions">{[['paired-trials.csv','全部85对试验 CSV'],['source-trials.csv','原始220行记录'],['protocol.json','后续统计协议'],['results.json','五样例完整结果'],['release-audit.json','独立发布复核'],['query-statistics-results.svg','科学图 SVG']].map(([file,label])=><a key={file} download href={`${base}${file}`}>{label} ↗</a>)}</div><p className="cr-hash">原始计时报告 SHA-256：{report.source_report_sha256}<br/>后续统计报告 SHA-256：{report.report_sha256}</p></details>
    <div className="cr-actions"><a download href={`${base}${report.package.filename}`}>完整统计复算证据 ZIP ↗</a><a download href={`${base}original-native-query-evidence.zip`}>原始 CPU 完整证据 ZIP ↗</a></div>
  </section>;
}
