import report from '../../../shared/result-focus-v5.json';
import {useComparisonAnchor} from './useComparisonAnchor';
import './ResultFocusSummary.css';
type Metric={label:string;value:number;unit:string;tone:string};
type Reduction={id:string;name:string;reduction_percent:number};
type Ratio={id:string;name:string;minimum:number;maximum:number};
type Story={id:string;category:string;headline:string;value:number;unit:string;value_note:string;context:string;baseline:string;coverage:string;controls:string;detail_href:string;package_url:string;metrics?:Metric[];points?:(Reduction|Ratio)[]};
const stories:Story[]=report.stories;
function EvidenceChart({story}:{story:Story}){
  if(story.id==='real-source-query'){
    const points=story.points!.filter((p):p is Ratio=>'minimum' in p),top=Math.ceil(Math.max(...points.map(p=>p.maximum))),project=(v:number)=>106-84*v/top;
    return <div className="rf-source-points"><svg viewBox="0 0 320 128" role="img" aria-label="二十个真实地形窗口三轮独立进程的精确P2对面带查询耗时比值范围"><line x1="13" x2="306" y1={project(1)} y2={project(1)} stroke="#cad8ce" strokeDasharray="3 3"/>{points.map((p,i)=><g key={p.id}><title>{`${p.name} · P₂ / 面带 ${p.minimum.toFixed(3)}–${p.maximum.toFixed(3)}×`}</title><line x1={19+14*i} x2={19+14*i} y1={project(p.minimum)} y2={project(p.maximum)} stroke="#83b5a3" strokeWidth="3"/><circle cx={19+14*i} cy={project(p.minimum)} r="3" fill="#299479"/><circle cx={19+14*i} cy={project(p.maximum)} r="3" fill="#299479"/></g>)}<text x="13" y="123">20 个窗口 · 全部 60 组实测</text><text x="306" y="16" textAnchor="end">P₂ / 面带耗时 · 倍</text></svg></div>;
  }
  if(story.metrics){const max=Math.max(...story.metrics.map(v=>v.value));return <div className="rf-bars" aria-label="当前四次曲面的六种保存模型全域E₂对照，误差越低越好">{story.metrics.map(m=><div className={`rf-bar-row rf-${m.tone}`} key={m.label}><span>{m.label}</span><i style={{width:`${100*m.value/max}%`}}/><output>{m.value.toExponential(3)}</output></div>)}<small>全域 E₂ / m² · P₂ 高阶控制更低</small></div>;}
  if(story.id==='real-hybrid'){const points=story.points!.filter((p):p is Reduction=>'reduction_percent' in p),max=Math.ceil(Math.max(...points.map(p=>p.reduction_percent))*2)/2||1,min=Math.min(0,Math.floor(Math.min(...points.map(p=>p.reduction_percent))*2)/2),project=(v:number)=>106-78*(v-min)/(max-min||1);return <div className="rf-source-points"><svg viewBox="0 0 320 128" role="img" aria-label="全部二十真实源样区在8192字节上限下相对同等共享拟合双对角线P1的误差降低，含三个失利样区"><line x1="13" x2="306" y1={project(0)} y2={project(0)} stroke="#dbe5df"/>{points.map((p,i)=><g key={p.id}><title>{`${p.name} · E₂ 降低 ${p.reduction_percent.toFixed(4)}%`}</title><line x1={19+14*i} x2={19+14*i} y1={project(0)} y2={project(p.reduction_percent)} stroke="#bfd8ce"/><circle cx={19+14*i} cy={project(p.reduction_percent)} r="3.7" fill={p.reduction_percent<0?'#b77550':'#299479'}/></g>)}<text x="13" y="123">20 个样区 · 同完整文件上限</text><text x="306" y="16" textAnchor="end">E₂ 降幅 / %</text></svg></div>;}
  const points=story.points!.filter((p):p is Ratio=>'minimum' in p),min=Math.floor(Math.min(...points.map(p=>p.minimum))*10)/10,max=Math.ceil(Math.max(...points.map(p=>p.maximum))*10)/10,project=(v:number)=>116+174*(v-min)/(max-min);
  return <div className="rf-cpu-ranges"><svg viewBox="0 0 320 128" role="img" aria-label="全部五个CPU样例在三次独立进程的实测比值范围"><line x1={project(1)} x2={project(1)} y1="6" y2="105" stroke="#dbe5df" strokeDasharray="3 3"/>{points.map((p,i)=><g key={p.id}><title>{`${p.name} · ${p.minimum.toFixed(3)}–${p.maximum.toFixed(3)}×`}</title><text x="0" y={17+21*i}>{['二次延展','线性调制','8 条面带','32 条面带','128 条面带'][i]}</text><line x1={project(p.minimum)} x2={project(p.maximum)} y1={13+21*i} y2={13+21*i} stroke="#83b5a3" strokeWidth="3"/><circle cx={project(p.minimum)} cy={13+21*i} r="3" fill="#299479"/><circle cx={project(p.maximum)} cy={13+21*i} r="3" fill="#299479"/></g>)}<text x="116" y="124">1.0×</text><text x="290" y="124" textAnchor="end">{max.toFixed(1)}×</text></svg></div>;
}
export default function ResultFocusSummary(){
  useComparisonAnchor('validated-advantages');
  return <section id="validated-advantages" className="rf-summary" aria-labelledby="rf-title"><div className="rf-heading"><div><span className="cr-eyebrow">GUGIS 对比结果 / 更强基线 / 完整证据</span><h2 id="rf-title">用更强的对照，验证优势。</h2></div><p>曲面精度、真实地形和查询效率分别比较。主结果采用 Pₜ 完整自适应贪心和同等共享拟合的双对角线强控制；全部预算、较强方法与不利结果可复查。</p></div><div className="rf-primary">{stories.map((s,i)=><article className="rf-card" key={s.id} data-result={s.id}><span className="rf-category"><b>0{i+1}</b>{s.category}</span><h3>{s.headline}</h3><div className="rf-result"><strong>{s.value.toFixed(s.unit==='%'||s.unit==='×'?2:0)}<small>{s.unit}</small></strong><span>{s.value_note}</span></div><p className="rf-context">{s.context}</p><EvidenceChart story={s}/><p className="rf-coverage">{s.coverage}</p><p className="rf-baseline">对照：{s.baseline}</p><p className="rf-controls">{s.controls}</p><div className="rf-actions"><a href={s.detail_href}>查看完整结果 ↗</a><a download href={s.package_url} aria-label={`${s.category}完整证据包`}>证据 ZIP ↓</a></div></article>)}</div>
    <div className="rf-secondary" aria-label="另外两项已核验完整文件收益">{report.secondary.map(c=><article key={c.id}><span>{c.id==='source-function'?'同函数矢量编码':'ArcGIS 兼容同几何'}</span><strong>{c.value.toFixed(1)}<small>%</small></strong><div><h3>{c.label}</h3><p>{c.baseline} · {c.scope}</p></div><a href={c.detail_href}>查看 ↗</a></article>)}</div><p className="rf-footnote">E₂ 为全域函数误差；文件比较均计入实际字节，查询比较为本机 CPU。Pₜ 按论文的区域优先级和选边决策完整细分；这是有限预算本机复现，不是作者原软件或渐近证明；ArcGIS 软件的同机加载、帧率与内存仍待测。</p></section>;
}
