import {useEffect,useMemo,useState} from 'react';
import compactReport from '../../../shared/source-global-fit-ui-v1.json';
import {loadSourceFitModel} from './loadSourceFitModel';
import {loadSourceModel} from './loadSourceModel';
import {prepareSourceBandQuery,prepareRegularGridQuery,type SourceBandModel,type RegularHeightGrid} from './sourceRuledBandMath';
import {useComparisonAnchor} from './useComparisonAnchor';
import './SourceFitResults.css';
type Entry={id:string;method:string;binary_filename:string;binary_bytes:number;binary_sha256:string;e2_m2:number;continuous_bound_m:number;ruled_cells:number;p1_triangles:number;fit_status?:string;original_e2_m2?:number;original_maximum_m?:number};
const report={...compactReport,cases:compactReport.cases.map(c=>({...c,models:Object.fromEntries(Object.entries(c.models).map(([id,values])=>[id,{id,...Object.fromEntries(compactReport.fields.map((field,i)=>[field,values[i]??undefined]))}])) as Record<string,Entry>}))};
type Site=typeof report.cases[number];
const base='/research/source-global-fit-v1/',labels:Record<string,string>={'p1-fit':'同等拟合 P1 三角带','ruled-fit':'共享拟合纯直纹面带','hybrid-fit':'共享拟合混合表达','p1-local':'原两对角线 P1','hybrid-local':'原混合表达','ruled':'原纯直纹面带'},methods=['p1-fit','ruled-fit','hybrid-fit'] as const;
const reduce=(a:number,b:number)=>a===b?0:100*(1-a/b),pct=(p:number)=>Math.abs(p).toFixed(Math.abs(p)<1?4:2),coordinates=Array.from({length:17},(_,i)=>Number((-32+(i+.5)*64/17).toFixed(2)));
function entry(site:Site,id:string|null):Entry|null{return id?site.models[id]:null;}
function Demo({site,entries}:{site:Site;entries:Entry[]}){
  const [loaded,setLoaded]=useState<{models:SourceBandModel[];grid:RegularHeightGrid}|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[x,setX]=useState(.27),[y,setY]=useState(-1.41);const key=entries.map(e=>e.id).join(',');
  useEffect(()=>{const abort=new AbortController();setLoaded(null);setError('');Promise.all([Promise.all(entries.map(e=>loadSourceFitModel(`${base}${site.id}/${e.binary_filename}`,e.binary_bytes,e.binary_sha256,site.origin_bng,abort.signal))),loadSourceModel(`/research/source-native-bands-v1/${site.id}/${site.regular_grid.filename}`,site.regular_grid.bytes,site.regular_grid.sha256,site.origin_bng,abort.signal)]).then(([models,source])=>{if(source.kind!=='grid')throw new Error('原始 Float32 源高程格类型不符');if(!abort.signal.aborted)setLoaded({models,grid:source.model});}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'读取失败');});return()=>abort.abort();},[site.id,key,retry]);
  const functions=useMemo(()=>loaded?.models.map(prepareSourceBandQuery)??null,[loaded]),source=useMemo(()=>loaded?prepareRegularGridQuery(loaded.grid):null,[loaded]);const heatmaps=useMemo(()=>functions&&source?functions.map(fn=>coordinates.flatMap((yy,j)=>coordinates.map((xx,i)=>({i,j,x:xx,y:yy,delta:fn.query(xx,yy)!.height-source.query(xx,yy)!.height})))):[],[functions,source]);const scale=heatmaps.length?Math.max(.001,...heatmaps.flatMap(m=>m.map(p=>Math.abs(p.delta)))):.001;
  if(error)return <p role="alert">{error} <button onClick={()=>setRetry(v=>v+1)}>重试共享拟合模型</button></p>;
  if(!loaded||!source||!functions)return <p role="status">正在核验当前三种拟合模型与原始源高程格的完整文件和 SHA-256…</p>;
  const reference=source.query(x,y)!;
  return <div className="sfit-demo"><div className="pr-query-controls">{(['X','Y'] as const).map((name,i)=><label key={name}>局部 {name} / m<input type="range" aria-label={`共享拟合原生同步查询${name}`} min="-31.9" max="31.9" step=".01" value={i?y:x} onChange={e=>(i?setY:setX)(Number(e.target.value))}/><output>{(i?y:x).toFixed(2)}</output></label>)}</div><p>同一点 · BNG E {reference.easting.toFixed(2)} / N {reference.northing.toFixed(2)} m · 源函数 Z {reference.height.toFixed(6)} m ODN</p><div className="sfit-native">{entries.map((e,k)=>{const q=functions[k].query(x,y)!;return <article key={e.id}><h3>{labels[e.method]}</h3><p>{e.binary_bytes.toLocaleString()} B · {e.ruled_cells} 个面带单元 / {e.p1_triangles} 个三角面</p><svg role="img" aria-label={`${labels[e.method]}同色标源函数误差热图，点击同步查询`} viewBox="0 0 300 300">{heatmaps[k].map(p=>{const t=Math.min(1,Math.abs(p.delta)/scale),zero=[248,250,247],end=p.delta<0?[94,142,174]:[190,113,72],colour=`rgb(${zero.map((v,i)=>Math.round(v+(end[i]-v)*t)).join(',')})`;return <rect key={p.i+17*p.j} x={27+14.4*p.i} y={12+14.4*(16-p.j)} width="14.45" height="14.45" fill={colour} data-x={p.x} data-y={p.y} data-delta={p.delta} onClick={()=>{setX(p.x);setY(p.y);}}><title>{`X ${p.x} / Y ${p.y} m · Δz ${(p.delta*1000).toFixed(4)} mm`}</title></rect>;})}<circle cx={27+244.8*(x+32)/64} cy={12+244.8*(32-y)/64} r="4" fill="none" stroke="#234c40" strokeWidth="1.5" pointerEvents="none"/><text x="27" y="278">统一色阶 ±{(scale*1000).toFixed(3)} mm</text><text x="27" y="295">蓝：较低 · 白：接近源值 · 橙：较高</text></svg><p>Z {q.height.toFixed(6)} m<br/>相对源函数 Δz {(1000*(q.height-reference.height)).toFixed(4)} mm<br/>梯度 [{q.gradient.map(v=>v.toFixed(6)).join(', ')}]<br/>原生类型 {q.kind==='ruled-strip'?'直纹面带':'三角带'} · 单元 {q.primitive}</p></article>;})}</div><p>三幅图使用相同 289 个展示点及同一色阶。点击色块或用滑条键盘操作会查询实际保存的原生函数，不会重新拟合。全域 E₂ 的排序不保证每一点误差都更小；拟合后也不强制经过原始高程节点。</p></div>;
}
export default function SourceFitResults(){
  useComparisonAnchor('source-fit-results');const [siteId,setSiteId]=useState(report.cases[0].id),[mode,setMode]=useState<'budget'|'target'>('budget'),[budget,setBudget]=useState(8192),[target,setTarget]=useState(.1),[demo,setDemo]=useState(false);const site=report.cases.find(c=>c.id===siteId)!,row=mode==='budget'?site.byte_pairs.find(p=>p.byte_ceiling===budget)!:site.target_pairs.find(p=>p.height_target_m===target)!,hybrid=entry(site,row['hybrid-fit']),p1=entry(site,row['p1-fit']),allRows=report.cases.map(c=>({site:c,row:mode==='budget'?c.byte_pairs.find(p=>p.byte_ceiling===budget)!:c.target_pairs.find(p=>p.height_target_m===target)!})),wins=allRows.filter(({site,row})=>{const h=entry(site,row['hybrid-fit']),p=entry(site,row['p1-fit']);return h&&p&&h.e2_m2<p.e2_m2;}).length,entries=methods.map(k=>entry(site,row[k])).filter((e):e is Entry=>!!e),a=report.aggregates;
  return <section id="source-fit-results" className="sfit-results" aria-labelledby="sfit-title"><div className="cr-heading"><div><span className="cr-eyebrow">真实 DTM / 共享 C⁰ 系数 / 同等优化条件</span><h2 id="sfit-title">让每一个保存的字节，表达更准确的地形。</h2><p>2,940 个原生模型中 {a.fitting.e2_strict_improvements.toLocaleString()} 个全域 E₂ 严格下降，其余 {a.fitting.exact_identities} 个是完整源函数的原样保留。所有网格、类型、索引和完整文件大小保持不变。三角带采用相同的共享拟合机会。</p></div><div className="sfit-selects"><label>原始真实样区<select aria-label="共享拟合真实地形样区" value={siteId} onChange={e=>setSiteId(e.target.value)}>{report.cases.map(c=><option key={c.id} value={c.id}>{c.name.replace(' · 英国环境署裸地 DTM','')}</option>)}</select></label><label>比较条件<select aria-label="共享拟合比较条件" value={mode} onChange={e=>setMode(e.target.value as 'budget'|'target')}><option value="budget">相同完整文件上限</option><option value="target">相同连续最大误差目标</option></select></label>{mode==='budget'?<label>文件上限<select aria-label="共享拟合文件预算" value={budget} onChange={e=>setBudget(Number(e.target.value))}>{site.byte_pairs.map(p=><option key={p.byte_ceiling} value={p.byte_ceiling}>{p.byte_ceiling.toLocaleString()} B</option>)}</select></label>:<label>源函数最大差<select aria-label="共享拟合最大误差目标" value={target} onChange={e=>setTarget(Number(e.target.value))}>{site.target_pairs.map(p=><option key={p.height_target_m} value={p.height_target_m}>{p.height_target_m*100} cm</option>)}</select></label>}</div></div>
    <div className="sfit-overview"><article><span>当前混合 / 同等拟合 P1 · 全域 E₂</span><strong>{hybrid&&p1?`${pct(reduce(hybrid.e2_m2,p1.e2_m2))}%`:'—'}<small>{hybrid&&p1?(hybrid.e2_m2<p1.e2_m2?'降低':hybrid.e2_m2>p1.e2_m2?'更高':'相同'):'无可比候选'}</small></strong><p>当前条件 {wins}/20 样区更低；8,192 B 固定上限下 17/20 更低，3/20 P1 更低。</p></article><article><span>当前混合 · 原结构拟合前后</span><strong>{hybrid?`${pct(reduce(hybrid.e2_m2,hybrid.original_e2_m2!))}%`:'—'}<small>全域 E₂ 降低</small></strong><p>{hybrid?`完整文件 ${hybrid.binary_bytes.toLocaleString()} → ${hybrid.binary_bytes.toLocaleString()} B；结构与 XY 不变。`:'固定候选中没有达到当前最大差目标的模型。'}</p></article><article><span>全部候选的最大误差变化</span><strong>{a.fitting.maximum_increases}<small>/ 2,940</small></strong><p>拟合后连续最大差超过原值及余量；L₂ 更低不代表最大差更低。误差目标按拟合后的连续界选择。</p></article></div>
    <div className="cr-table"><table><caption>{mode==='budget'?`同一完整文件上限 ${budget.toLocaleString()} B · 实际文件可以不同`:`相对同一源函数的连续最大差 ≤ ${target*100} cm · 未达标模型保留为空`}</caption><thead><tr><th>方法</th><th>完整文件</th><th>全域 E₂ / m²</th><th>连续最大差界</th><th>面带 / 三角面</th></tr></thead><tbody>{[...methods,...['p1-local','ruled','hybrid-local'] as const].map(k=>{const e=entry(site,k.endsWith('-fit')?row[k as typeof methods[number]]:row.unfitted[k as 'p1-local'|'ruled'|'hybrid-local']);return <tr key={k}><th>{labels[k]}</th>{e?<><td>{e.binary_bytes.toLocaleString()} B</td><td>{e.e2_m2.toExponential(5)}</td><td>{(e.continuous_bound_m*100).toFixed(4)} cm</td><td>{e.ruled_cells} / {e.p1_triangles}</td></>:<td colSpan={4}>固定候选中无合格模型</td>}</tr>;})}</tbody></table></div>
    <p className="hs-scope">表中六种方法分别择优，网格和实际文件可能不同；上方“原结构拟合前后”比较当前混合模型与其同一原结构。每个样区使用原始 65 × 65 Float32 高程节点，比较全部 64 × 64 m 源插值函数。这里优化共享角点高程，不改变预先选好的类型与对角线；不等于全局最优混合结构。完整文件与运行内存分开。原全分辨率 P₂、规则栅格仍保留同一源函数；这项结果不表示独立地面测量精度、论文作者数据或 ArcGIS 软件跑分。</p><div className="cr-actions"><button aria-expanded={demo} aria-label="展开共享拟合原生同步查询" onClick={()=>setDemo(v=>!v)} disabled={!entries.length}>{demo?'收起共享拟合原生查询':'打开三种拟合模型同色标查询'}</button>{hybrid&&<a download href={`${base}${site.id}/${hybrid.binary_filename}`}>当前混合原生文件 ↗</a>}<a download href={`${base}${report.package.filename}`}>全部模型与完整证据 ZIP ↗</a><a download href={`${base}${site.id}/source-window.tif`}>原始一米 GeoTIFF ↗</a></div>
    {demo&&<Demo key={site.id+mode+budget+target} site={site} entries={entries}/>}
    <details className="cr-details"><summary>全部二十样区：当前条件、三角带更好的样区与未达目标</summary><div className="cr-table"><table><thead><tr><th>固定样区</th><th>拟合混合 E₂ / 文件</th><th>拟合 P1 E₂ / 文件</th><th>混合相对 P1</th><th>混合最大差界</th></tr></thead><tbody>{allRows.map(({site:c,row:p})=>{const h=entry(c,p['hybrid-fit']),t=entry(c,p['p1-fit']),change=h&&t?reduce(h.e2_m2,t.e2_m2):null;return <tr key={c.id}><th>{c.name.replace(' · 英国环境署裸地 DTM','')}</th><td>{h?`${h.e2_m2.toExponential(4)} / ${h.binary_bytes} B`:'无合格模型'}</td><td>{t?`${t.e2_m2.toExponential(4)} / ${t.binary_bytes} B`:'无合格模型'}</td><td className={change!==null&&change<0?'sfit-max-rise':'sfit-better'}>{change!==null?`${pct(change)}% ${change>0?'降低':change<0?'更高':'相同'}`:'无法比较'}</td><td>{h?`${(h.continuous_bound_m*100).toFixed(4)} cm`:'—'}</td></tr>;})}</tbody></table></div><img src={`${base}source-fit-results.svg`} loading="lazy" width="1100" height="865" alt="全部二十原始真实地形样区在8192字节上限下的共享拟合混合对同等拟合三角带E2比值，含三个失利样区"/></details>
    <details className="cr-details"><summary>2,940 个模型、同等拟合条件与完整独立核验</summary><p>二十样区 × 49 个整数张量网格 × 三种方法。三角带与混合的方向和类型来自上次已冻结的局部选择；本次不根据新结果调整。所有角点共用，边界线性函数一致，保持 C⁰，无 T 形接点，梯度仍可跳变。原节点不再要求插值通过。</p><p>8,192 B 下混合相对同等拟合 P1 的降幅为 {a.hybrid_vs_fitted_p1.minimum_reduction_percent.toFixed(4)}% 至 {a.hybrid_vs_fitted_p1.maximum_reduction_percent.toFixed(4)}%（负值表示更高）；全部十档预算 {a.hybrid_vs_fitted_p1.all_budget_wins}/200 更低。相对同等拟合纯面带，8,192 B 下 20/20 更低，降幅 {a.hybrid_vs_fitted_ruled.minimum_reduction_percent.toFixed(2)}%–{a.hybrid_vs_fitted_ruled.maximum_reduction_percent.toFixed(2)}%。所有 {a.fitting.fallbacks} 个回退和 {a.fitting.maximum_increases} 个最大差增长均公开。</p><p>独立 GL5 重新积分所有保存模型并检查连续最大值；数值 GL5 质量矩阵和源函数载荷检查全局 Galerkin 方程，冻结求解器逐字节重放。原生内核执行 {report.native_queries.toLocaleString()} 次高程、解析梯度、节点与坐标核验，另检查 {report.seam_height_pairs.toLocaleString()} 对边界值；文件 SHA-256、完整二进制读回与最大值见证点全部通过。Float64 余量不是区间证明。</p><div className="cr-actions">{[['selections.csv','所有拟合预算 / 目标 CSV'],['protocol.json','预先固定协议'],['results.json','全部候选与原控制'],['native-audit.json','原生查询与接缝'],['integral-audit.json','独立积分与 Galerkin'],['aggregate.json','完整汇总']].map(([file,label])=><a download key={file} href={`${base}${file}`}>{label} ↗</a>)}</div><p className="cr-hash">结果 SHA-256：{report.report_sha256}<br/>完整 ZIP SHA-256：{report.package.sha256}</p></details>
  </section>;
}
