import {useState} from 'react';
import report from '../../../shared/source-query-display-v1.json';
import {useComparisonAnchor} from './useComparisonAnchor';
import './QueryStatisticsResults.css';
import './SourceQueryResults.css';
const base='/research/source-query-v1/',families=['compact_ruled','generic_ruled','exact_p2','regular_grid'] as const;
const labels=['GUGIS 直接查询','原直纹面查询','精确 P₂ 三角面','Float32 规则栅格'],colours=['#21866e','#92aea0','#b29360','#577d98'];
export default function SourceQueryResults(){
  useComparisonAnchor('source-query-results');
  const [id,setId]=useState('manchester-centre'),item=report.cases.find(c=>c.id===id)!,a=report.aggregate.p2_over_compact,g=report.aggregate.grid_over_compact,maximum=Math.max(...item.repetitions.flatMap(r=>Object.values(r.latency_median_ns)));
  return <section className="qs-results sq-results" id="source-query-results" aria-labelledby="sq-title"><div className="cr-heading"><div><span className="cr-eyebrow">真实 DTM / 同源函数 / 四种查询实现</span><h2 id="sq-title">从保存的面带，直接查询地形。</h2><p>20 个原始 1 m DTM 窗口 × 三个新 Node 进程。全部 {a.wins}/{a.total} 组的当前 P₂ 查询耗时中位数更高，实测比值 {a.minimum.toFixed(2)}–{a.maximum.toFixed(2)}×。</p></div><label className="qs-selector">查看同一地形的三轮结果<select aria-label="真实地形查询性能样区" value={id} onChange={e=>setId(e.target.value)}>{report.cases.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label></div>
    <div className="qs-metrics"><article><span>当前 P₂ / GUGIS 查询中位数</span><strong>{a.minimum.toFixed(2)}<small>–{a.maximum.toFixed(2)}×</small></strong><p>全部 60 组同设备实测范围，保留三次独立进程</p></article><article><span>旧直纹面查询 / 新直接查询</span><strong>{report.aggregate.generic_over_compact.minimum.toFixed(2)}<small>–{report.aggregate.generic_over_compact.maximum.toFixed(2)}×</small></strong><p>原生文件和高度函数不变，原控制点直接参与查询</p></article><article className="sq-raster"><span>规则栅格控制仍然更快</span><strong>{(1/g.maximum).toFixed(2)}<small>–{(1/g.minimum).toFixed(2)}×</small></strong><p>栅格 / GUGIS 耗时比 {g.minimum.toFixed(3)}–{g.maximum.toFixed(3)}，没有隐藏更强控制</p></article></div>
    <div className="sq-processes" aria-label="当前地形三轮四种方法的查询耗时中位数">{item.repetitions.map(r=><article key={r.repetition}><h3>独立进程 {r.repetition}<small>同一坐标 · 同一查询次数</small></h3>{families.map((family,i)=><div className="sq-latency" key={family}><span>{labels[i]}</span><i style={{width:`${100*r.latency_median_ns[family]/maximum}%`,background:colours[i]}}/><output>{r.latency_median_ns[family].toFixed(2)} ns</output></div>)}<p>P₂ / GUGIS：{r.ratios.p2_over_compact.toFixed(3)}×<br/>每轮查询 {r.queries_per_trial.toLocaleString()} 次，四种方法次数相同。</p></article>)}</div>
    <p className="qs-scope">计时涵盖点定位、高程、解析梯度和消费结果的校验和，解码、验证、准备与文件读写不在计时范围内。P₂ 与面带保留各自完整的原生查询接口；规则栅格返回较少元数据，接口和实现的差异会影响耗时。本组对比针对当前实现和固定窗口，未证明三角面方法的一般速度下限，也不是 ArcGIS 软件或 GPU 帧率测试。</p>
    <div className="cr-table"><table><caption>全部二十个窗口：P₂ / 直接面带查询耗时中位数之比；大于 1 表示面带更快</caption><thead><tr><th>原始地形窗口</th><th>进程 1</th><th>进程 2</th><th>进程 3</th><th>栅格 / 面带的完整范围</th></tr></thead><tbody>{report.cases.map(c=><tr key={c.id}><th>{c.name}</th>{c.repetitions.map(r=><td key={r.repetition}>{r.ratios.p2_over_compact.toFixed(3)}×</td>)}<td>{c.ranges.grid_over_compact.minimum.toFixed(3)}–{c.ranges.grid_over_compact.maximum.toFixed(3)}</td></tr>)}</tbody></table></div>
    <details className="cr-details"><summary>当前窗口的完整文件与执行控制点数</summary><div className="cr-table"><table><thead><tr><th>方法</th><th>完整文件 B</th><th>存储控制点</th><th>执行控制点</th><th>查询单元</th></tr></thead><tbody>{item.methods.map((m,i)=><tr key={m.family}><th>{labels[i]}</th><td>{m.binary_bytes.toLocaleString()}</td><td>{m.stored_points.toLocaleString()}</td><td>{m.execution_points.toLocaleString()}</td><td>{m.primitives.toLocaleString()}</td></tr>)}</tbody></table></div><p>新旧面带读取同一个 135,528 B 文件，新路径不保留用于查询的中间控制点。执行控制点数不是进程或堆内存测量；验证阶段仍调用原验证器，存在短期扩展。规则 Float32 栅格文件 16,980 B，比面带更小。P₂ 文件 694,376 B，表示同一源双线性函数。</p><div className="cr-actions">{['ruled.bin','source_p2.bin','regular-grid.bin'].map(name=><a download key={name} href={`${base}models/${item.id}/${name}`}>{name} ↗</a>)}</div></details>
    <details className="cr-details"><summary>完整协议、核验、失败记录与全部计时</summary><p>每种方法预热五轮。共同循环次数根据原面带与 P₂ 的三次校准中位数确定，目标 30 ms、上限 128 轮。四种方法的全部 24 种排列各执行一次，每种方法在四个位置各出现六次。三个进程顺序运行，未与本任务的构建或数值核验同时计时；系统后台负载未受控。</p><p>首次尝试因相对路径解析而在创建输出目录时失败，产生 0 条计时；失败记录保留。改用绝对路径的新尝试完整执行三轮，冻结代码和协议没有改变。{report.native_query_calls.toLocaleString()} 次原生调用核对了源公式、边界归属、高度、梯度、完整文件读回及越界拒绝。</p><p>三次范围是实际最小值和最大值，不是置信区间；未删除较慢进程或筛选城市。环境：{report.environment.cpu_model} · {report.environment.platform} {report.environment.architecture} · Node {report.environment.node}。</p><div className="cr-actions">{[['all-trials.csv','全部 5,760 条 CSV'],['protocol.json','计时前固定协议'],['native-audit.json','原生函数与接缝核验'],['failed-before-timing-receipt.json','计时前失败记录'],['results.json','完整结果与校验码']].map(([name,label])=><a download key={name} href={`${base}${name}`}>{label} ↗</a>)}</div><p className="cr-hash">报告 SHA-256：{report.report_sha256}<br/>源发布 SHA-256：{report.source_publication_sha256}</p></details>
    <div className="cr-actions"><a download href={`${base}${report.package.filename}`}>完整四方法证据 ZIP ↗</a><a download href={`${base}source-query-results.svg`}>全部实测科学图 SVG ↗</a><a href="#source-function-results">同函数精度与文件对比 ↗</a><a href="#native-query-repeat">五个解析函数的独立复测 ↗</a></div>
  </section>;
}
