import report from '../../../shared/validated-advantages-v1.json';
import {useComparisonAnchor} from './useComparisonAnchor';
import './ValidatedAdvantageSummary.css';
const categories=['论文式 P1 精度','真实源函数','ArcGIS 兼容格式','原生 CPU 查询'];
function metric(value:number,kind:string){return kind==='error-percent'?value.toExponential(3):kind==='cpu-ratio'?value.toFixed(1):value.toLocaleString();}
export default function ValidatedAdvantageSummary(){
  useComparisonAnchor('validated-advantages');
  return <section id="validated-advantages" className="va-summary" aria-labelledby="va-title"><div className="va-heading"><div><span className="cr-eyebrow">已核验结果 / 同源控制 / 可下载复算</span><h2 id="va-title">四项优势，各有清楚的比较对象。</h2></div><p>先看结果，再查看模型与复算证据。下列是固定研究样例；城市切换不会改变这些对标输入。</p></div><div className="va-cards">{report.claims.map((claim,i)=><article key={claim.id} className="va-card" data-claim={claim.id}><span className="va-category"><b>0{i+1}</b>{categories[i]}</span><h3>{claim.label}</h3><strong className="va-number">{claim.value.toFixed(claim.kind==='error-percent'||claim.kind==='cpu-ratio'?2:1)}<small>{claim.kind==='cpu-ratio'?'×':'%'}</small></strong><p className="va-context">{claim.context}</p><div className="va-paired-values"><dl><div><dt>GUGIS</dt><dd>{metric(claim.gugis_metric,claim.kind)}</dd></div><div><dt>参考方法</dt><dd>{metric(claim.baseline_metric,claim.kind)}</dd></div></dl><span>{claim.metric_unit}</span><div className="va-cost-track" aria-label={`GUGIS ${claim.metric_unit} 为参考的 ${(100*claim.gugis_metric/claim.baseline_metric).toFixed(3)}%`}><i style={{width:`${100*claim.gugis_metric/claim.baseline_metric}%`}}/></div></div><p className="va-baseline">对照：{claim.baseline}</p><p className="va-evidence">{claim.evidence}</p><p className="va-scope">{claim.scope}</p><div className="va-actions"><a href={claim.detail_href}>查看完整结果 <span aria-hidden="true">↗</span></a><a download href={claim.package_url} aria-label={`${categories[i]}完整证据包`}>证据 ZIP <span aria-hidden="true">↓</span></a></div></article>)}</div><p className="va-footnote">四种结果分别衡量误差、完整文件和 CPU 查询。ArcGIS 项是实际兼容文件对照；ArcGIS 软件的同机加载、帧率与内存数据仍待测。</p></section>;
}
