import {useEffect,useId,useMemo,useState} from 'react';
import report from '../../../shared/variable-curvature-display-v1.json';
import {preparePrincipalQuery,type PrincipalModel} from './principalRuledMath';
import {loadVariableModel} from './loadVariableModel';
import {useComparisonAnchor} from './useComparisonAnchor';
import PaperProjectionDisclosure from './PaperProjectionDisclosure';
import AdaptivePaperDisclosure from './AdaptivePaperDisclosure';
import './VariableCurvatureResults.css';
const base='/research/variable-curvature-v1/';
type Case=typeof report.cases[number];type Pair=Case['pairs'][number];
const sci=(n:number)=>n.toExponential(3),saving=(a:number,b:number)=>100*(1-a/b);
function outcome(a:number,b:number){const v=saving(a,b);return Math.abs(v)<1e-8?'持平':v>0?`降低 ${v.toFixed(2)}%`:`高于 ${(-v).toFixed(2)}%`;}
function SurfaceDemo({item,pair}:{item:Case;pair:Pair}){
  const [models,setModels]=useState<PrincipalModel[]|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[x,setX]=useState(12.7),[y,setY]=useState(-17.3),uid=useId();
  const descriptors=[pair.p1,pair.mean_hessian,pair.p2];
  useEffect(()=>{const abort=new AbortController();setModels(null);setError('');
    Promise.all(descriptors.map(e=>loadVariableModel(`${base}${item.id}/${e.binary_filename}`,e.binary_bytes,e.binary_sha256,abort.signal))).then(m=>{if(!abort.signal.aborted)setModels(m);}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'读取失败');});return()=>abort.abort();
  },[item.id,pair.budget,retry]);
  const functions=useMemo(()=>models?.map(preparePrincipalQuery)??null,[models]);
  if(error)return <p role="alert">{error} <button onClick={()=>setRetry(n=>n+1)}>重试变曲率模型</button></p>;
  if(!models||!functions)return <p role="status">正在校验三个完整原生模型…</p>;
  const r=item.source_frame,u=x*r[0][0]+y*r[1][0],v=x*r[0][1]+y*r[1][1],field=item.field,z=30+field.quadratic[0]*u*u+field.quadratic[1]*v*v+field.quartic[0]*u**4+field.quartic[1]*v**4,map=(x:number,y:number)=>`${25+3.3*(x+50)},${355-3.3*(y+50)}`;
  return <div className="vc-demo"><div className="pr-query-controls">{(['X','Y'] as const).map((label,i)=><label key={label}>同点 {label} / m<input aria-label={`变曲率同点查询${label}`} type="range" min="-49.9" max="49.9" step=".1" value={i?y:x} onChange={e=>(i?setY:setX)(Number(e.target.value))}/><output>{(i?y:x).toFixed(1)}</output></label>)}</div>
    <div className="vc-surfaces">{models.map((model,i)=>{
      let paths='';for(const p of model.patches){if(p.kind==='quadratic-ruled'){for(const ids of [p.left,p.right])paths+=ids.map((n,j)=>`${j?'L':'M'}${map(model.points[n][0],model.points[n][1])}`).join('');}else{const triangles=p.kind==='lagrange-triangle'?[[p.indices[0],p.indices[3],p.indices[5]]]:Array.from({length:p.indices.length-2},(_,j)=>p.indices.slice(j,j+3));for(const ids of triangles)paths+=ids.map((n,j)=>`${j?'L':'M'}${map(model.points[n][0],model.points[n][1])}`).join('')+'Z';}}
      const q=functions[i].query(x,y),clip=`${uid}-${i}`;
      return <article key={i}><h3>{['论文式 P1','平均 Hessian 面带','固定层级 P2 控制'][i]}</h3><p>{descriptors[i].binary_bytes.toLocaleString()} B · {functions[i].primitives.toLocaleString()} 个原生面</p><svg role="img" aria-label={`${['P1三角带','变曲率面带','P2三角控制'][i]}已保存模型水平投影`} viewBox="0 0 380 385"><defs><clipPath id={clip}><rect x="25" y="25" width="330" height="330"/></clipPath></defs><rect x="25" y="25" width="330" height="330" fill="#f6f9f5" stroke="#d6e3d8"/><path d={paths} clipPath={`url(#${clip})`} fill="none" stroke={['#628198','#238c76','#8a65a4'][i]} strokeWidth=".65"/><circle cx={25+3.3*(x+50)} cy={355-3.3*(y+50)} r="4" fill="#d66b54" stroke="white"/><text x="25" y="376">同一 100 × 100 m 物理范围 · XY 投影</text></svg><p className="vc-point">{q?<>Z {q.height.toFixed(9)} m<br/>同点 Δz {(1000*(q.height-z)).toFixed(6)} mm<br/>坡度 {(Math.atan(Math.hypot(...q.gradient))*180/Math.PI).toFixed(6)}°</>:'该点未覆盖'}</p></article>;
    })}</div><p>曲线节点仅显示水平结构，图中连线不代表曲面被线性化。高程和坡度由下载文件中的原生函数直接计算；边界取最小编号命中面，图像只裁剪显示范围，全部范围外控制点仍计入文件代价。</p></div>;
}
export default function VariableCurvatureResults(){
  useComparisonAnchor('variable-curvature-results');
  const [field,setField]=useState('anisotropic-quartic'),[angle,setAngle]=useState(30),[budget,setBudget]=useState(2048),[demo,setDemo]=useState(false),item=report.cases.find(c=>c.field.id===field&&c.angle_degrees===angle)!,pair=item.pairs.find(p=>p.budget===budget)!,a=pair.p1,b=pair.mean_hessian;
  const cases=report.cases.filter(c=>c.field.id===field),pairs=cases.flatMap(c=>c.pairs),wins=pairs.filter(p=>p.mean_hessian.e2_m2<p.p1.e2_m2).length,reduction=saving(b.e2_m2,a.e2_m2);
  return <section id="variable-curvature-results" className="vc-results" aria-labelledby="vc-title"><div className="cr-heading"><div><span className="cr-eyebrow">变曲率验证 / 126 组固定预算 / 保留全部失利</span><h2 id="vc-title">从常曲率走向变曲率，验证优势在哪里成立。</h2><p>强方向性四次曲面在 63 / 63 组预算下优于论文式 P1，E₂ 降低 33.81%–90.16%；另一组四次曲面仅 31 / 63 组成立。平均 Hessian 方向需要结合地形类型选择。</p></div><div className="vc-selects"><label>预先固定曲面<select aria-label="变曲率对标曲面" value={field} onChange={e=>setField(e.target.value)}><option value="anisotropic-quartic">强方向性四次曲面</option><option value="published-quartic">既有四次曲面</option></select></label><label>源方向<select aria-label="变曲率源方向" value={angle} onChange={e=>setAngle(Number(e.target.value))}>{cases.map(c=><option key={c.id} value={c.angle_degrees}>{c.angle_degrees}°</option>)}</select></label><label>P1 预算<select aria-label="变曲率论文预算" value={budget} onChange={e=>setBudget(Number(e.target.value))}>{item.pairs.map(p=><option key={p.budget} value={p.budget}>N = {p.budget.toLocaleString()}</option>)}</select></label></div></div>
    <div className="vc-metrics"><article className={reduction<0?'vc-loss':''}><span>当前面带相对论文式 P1 · 全域 E₂</span><strong>{Math.abs(reduction).toFixed(2)}<small>% {reduction<0?'更高':'降低'}</small></strong><p>{sci(b.e2_m2)} / {sci(a.e2_m2)} m² · 面带 / P1</p></article><article><span>同编码完整文件 · 当前节省</span><strong>{saving(b.binary_bytes,a.binary_bytes).toFixed(1)}<small>%</small></strong><p>{b.binary_bytes.toLocaleString()} / {a.binary_bytes.toLocaleString()} B · 面带 / P1</p></article><article><span>当前曲面 · 全部角度与预算</span><strong>{wins}<small>/ {pairs.length} 组误差更低</small></strong><p>7 个方向 × 9 档预算 · 所有结果均保留</p></article></div>
    <div className="vc-controls"><p><strong>固定坐标轴面带：</strong>E₂ {sci(pair.world.e2_m2)} m²；平均 Hessian 方向相对它{outcome(b.e2_m2,pair.world.e2_m2)}。</p><p><strong>P2 高阶控制：</strong>E₂ {sci(pair.p2.e2_m2)} m²，{pair.p2.binary_bytes.toLocaleString()} B；当前面带相对它{outcome(b.e2_m2,pair.p2.e2_m2)}。P2 与面带都受当前 P1 的文件和面数双重上限约束，实际花费可能不同。</p><p>P2 在细预算下通常更准确。本对标比较有限候选表达空间，不证明面带普遍优于 P2；P2 控制沿用固定 P1 二分层级，未做全局最优 P2 网格搜索。</p></div>
    <div className="cr-actions"><button aria-expanded={demo} aria-label="展开变曲率原生查询" onClick={()=>setDemo(v=>!v)}>{demo?'收起变曲率原生查询':'查看三个真实模型与同点查询'}</button>{[['当前 GUGIS',b],['论文式 P1',a],['P2 控制',pair.p2]].map(([label,e])=>{const m=e as typeof a;return <a key={String(label)} download href={`${base}${item.id}/${m.binary_filename}`}>{String(label)} 模型 ↗</a>;})}<a download href={`${base}${report.package.filename}`}>完整 126 组证据 ZIP ↗</a></div>
    {demo&&<SurfaceDemo key={item.id+budget} item={item} pair={pair}/>}
    <AdaptivePaperDisclosure/>
    <PaperProjectionDisclosure/>
    <details className="cr-details"><summary>两种曲面、全部 14 个方向在当前预算下的结果</summary><div className="cr-table"><table><caption>N = {budget.toLocaleString()} · 每种方法覆盖同一 10,000 m² · E₂ 是全域积分误差</caption><thead><tr><th>曲面 / 方向</th><th>面带 / P1 E₂ m²</th><th>面带相对 P1</th><th>P2 E₂ m²</th><th>面带 / P1 / P2 文件 B</th></tr></thead><tbody>{report.cases.map(c=>{const p=c.pairs.find(p=>p.budget===budget)!;return <tr key={c.id}><th>{c.field.id==='anisotropic-quartic'?'强方向性':'既有四次'} · {c.angle_degrees}°</th><td>{sci(p.mean_hessian.e2_m2)} / {sci(p.p1.e2_m2)}</td><td>{outcome(p.mean_hessian.e2_m2,p.p1.e2_m2)}</td><td>{sci(p.p2.e2_m2)}</td><td>{p.mean_hessian.binary_bytes.toLocaleString()} / {p.p1.binary_bytes.toLocaleString()} / {p.p2.binary_bytes.toLocaleString()}</td></tr>;})}</tbody></table></div><img src={`${base}variable-curvature-results.svg`} loading="lazy" width="1100" height="770" alt="变曲率两曲面全预算误差图和全部126组方向预算胜负矩阵，保留P2控制和面带失利"/></details>
    <details className="cr-details"><summary>固定协议、完整原始结果与复算范围</summary><p>实验先固定 2 个严格凸四次曲面、7 个旋转角度、9 档预算。每例 180 个候选：三类方向 × 6 档沿曲线分段 × 10 档跨带分段，合计 2,520 个。只有同时不可能满足任一预算的候选不做积分，其预测完整字节数与排除理由仍保留。</p><p>每例选取最小 E₂ 的合格候选，始终同时满足论文式 P1 的完整 GPR3 字节数和原生面数上限。完整 Float64 XYZ、索引、面记录、共同裁剪头，以及旋转后范围外的控制点全部计价。候选搜索成本未作为查询性能收益。</p><p>P1 复用论文式 L₂ 贪心区域选择、L₁ 二分选边和三角带打包；未增加 C⁰ 细分闭合。局部 Hessian 随位置变化，当前方向来自解析全域平均 Hessian，不声称已解决带噪真实 DTM 的方向估计。</p><p>{report.native_model_count.toLocaleString()} 个已保存原生函数均通过独立七节点全域积分复核与 {report.native_internal_queries.toLocaleString()} 次同点高程、梯度核验。E₂ = √∫(z模型−z源)² dA，单位 m²；查询抽样 RMS 与最大差只用于诊断，不代替积分误差或连续最大误差证明。Float64 验算不是区间证明，未执行作者原始软件或 ArcGIS，未测 GPU、查询耗时、内存或实测地面精度。</p><div className="cr-actions">{[['pairs.csv','126 组结果 CSV'],['protocol.json','预先固定协议'],['results.json','全部候选与失败结果'],['native-audit.json','原生查询审计'],['integral-audit.json','独立积分审计'],['variable-curvature-results.svg','科学图 SVG']].map(([file,label])=><a download key={file} href={`${base}${file}`}>{label} ↗</a>)}</div><p className="cr-hash">结果 SHA-256：{report.report_sha256}<br/>证据 ZIP SHA-256：{report.package.sha256}</p></details>
  </section>;
}
